### ISSUE TITLE
ConfigStatusInfoEvent Causes error

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#107]
I have V 0.12 and I'm still seeing these errors:
```
2020-01-31 12:20:36,266[                    MyRule]ERROR|            on_error: Error: Error in on_sse_event: Unknown Event: ConfigStatusInfoEvent for {'topic': 'smarthome/things/zwave:device:controller:node9/config/status', 'payload': '{"configStatusMessages":[]}', 'type': 'ConfigStatusInfoEvent'}
Traceback (most recent call last):
KeyError: 'ConfigStatusInfoEvent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nick/Scripts/HABApp/HABApp/util/wrapper.py", line 79, in f
    return func(*args, **kwargs)
  File "/home/nick/Scripts/HABApp/HABApp/openhab/oh_connection.py", line 103, in on_sse_event
    event = get_event(event_dict)
  File "/home/nick/Scripts/HABApp/HABApp/openhab/events/__init__.py", line 27, in get_event
    raise ValueError(f'Unknown Event: {event_type:s} for {_in_dict}')
ValueError: Unknown Event: ConfigStatusInfoEvent for {'topic': 'smarthome/things/zwave:device:controller:node9/config/status', 'payload': '{"configStatusMessages":[]}', 'type': 'ConfigStatusInfoEvent'}
2020-01-31 12:20:36,524[                    MyRule]ERROR|            on_error: Error: Error in on_sse_event: Unknown Event: ConfigStatusInfoEvent for {'topic': 'smarthome/things/zwave:device:controller:node9/config/status', 'payload': '{"configStatusMessages":[]}', 'type': 'ConfigStatusInfoEvent'}
Traceback (most recent call last):
KeyError: 'ConfigStatusInfoEvent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nick/Scripts/HABApp/HABApp/util/wrapper.py", line 79, in f
    return func(*args, **kwargs)
  File "/home/nick/Scripts/HABApp/HABApp/openhab/oh_connection.py", line 103, in on_sse_event
    event = get_event(event_dict)
  File "/home/nick/Scripts/HABApp/HABApp/openhab/events/__init__.py", line 27, in get_event
    raise ValueError(f'Unknown Event: {event_type:s} for {_in_dict}')
ValueError: Unknown Event: ConfigStatusInfoEvent for {'topic': 'smarthome/things/zwave:device:controller:node9/config/status', 'payload': '{"configStatusMessages":[]}', 'type': 'ConfigStatusInfoEvent'}
```

**Comment by spacemanspiff2007** [comment]
This is already fixed in the current dev branch, I just forgot to update the other issue

**Comment by spacemanspiff2007** [comment]
#108
