### ISSUE TITLE
"Line too long" issue

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#218]
This problem has cropped up again
```
2021-05-06 19:17:14,209[                    HABApp]ERROR|   process_exception:      new_value = b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\xfc\x00\x00\x00\xfc\x08\x06\x00\x00\x00S\xab\xc9g\x00\x00\x00\tpHYs\x00\x00\x0b\x13\x00\x00\x0b\x13\x01\x00\x9a\x9c\x18\x00\x00\x05 iTXtXML:com.adobe.xmp\x00\x00\x00\x00\x00<?xpacket begin="\xef\xbb\xbf" id="W5M0MpCehiHzreSzNTczkc9d"?> <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.6-c140 79.160451, 2017/05/06-01:08:21        "> <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"> <rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/" xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/" xmlns:stEvt="http://ns.adobe.com/xap/1.0/sType/ResourceEvent#" xmp:CreatorTool="Adobe Photoshop CC 2018 (Macintosh)" xmp:CreateDate="2018-08-17T14:17:50-04:00" xmp:ModifyDate="2018-08-20T07:38:16-04:00" xmp:MetadataDate="2018-08-20T07:38:16-04:00" dc:format="image/png" photoshop:ColorMode="3" photoshop:ICCProfile="sRGB IEC61966-2.1" xmpMM:InstanceID="xmp.iid:2b71840f-16df-42a0-83b9-f9c8aa733a35" xmpMM:DocumentID="xmp.did:2b71840f-16df-42a0-83b9-f9c8aa733a35" xmpMM:OriginalDocumentID="xmp.did:2b71840f-16df-42a0-83b9-f9c8aa733a35"> <xmpMM:History> <rdf:Seq> <rdf:li stEvt:action="created" stEvt:instanceID="xmp.iid:2b71840f-16df-42a0-83b9-f9c8aa733a35" stEvt:when="2018-08-17T14:17:50-04:00" stEvt:softwareAgent="Adobe Photoshop CC 2018 (Macintosh)"/> </rdf:Seq> </xmpMM:History> </rdf:Description> </rdf:RDF> </x:xmpmeta> <?xpacket end="r"?>\x0f-Z\xfc\x00\x00%1IDATx\x9c\xed\xddy\x9c\x14\xe5\x9d\xc7\xf1\xcf\xd3\'0\x03r\r*A\x01!\x80 \xc8\xa1B\x8cD9\xa2\x06\x83\x98u\x1dL\x14\x11Y\x89\x83\xeb\x95\x18\r\xabF$\xba,\xac!&\x08(\x89\xb71\x081\x06\xaf\x80\x12\x10p\xc3\xa1\x82\x80\xa2\\\x03\x08\x820\x0c\x83\x0c\x03\xd3W=\xfbG\x83\xc1a\x86\xae\xae\xa9\xea\xae\xee\xfa\xbd_\xaf~\xf9\x9a\xa1\xea\xa9\x9f\x03\xdf\xa9\xeb9\x94\xd6\x1a!\x847\xf8\xb2]\x80\x10"s$\xf0Bx\x88\x04^\x08\x0f\x91\xc0\x0b\xe1!\x12x!<D\x02/\x84\x87H\xe0\x8...
2021-05-06 19:17:14,209[                    HABApp]ERROR|   process_exception:      RawValue = <class 'HABApp.openhab.definitions.values.RawValue'>
2021-05-06 19:17:14,210[                    HABApp]ERROR|   process_exception:     ..................................................
2021-05-06 19:17:14,210[                    HABApp]ERROR|   process_exception:
2021-05-06 19:17:14,210[                    HABApp]ERROR|   process_exception: AssertionError: <class 'bytes'>
2021-05-06 19:17:15,064[ HABApp.openhab.connection]ERROR| start_sse_event_listener: SSE request Error: Line is too long
2021-05-06 19:17:15,065[ HABApp.openhab.connection]ERROR| start_sse_event_listener: Traceback (most recent call last):
2021-05-06 19:17:15,066[ HABApp.openhab.connection]ERROR| start_sse_event_listener:   File "/home/nick/Scripts/HABApp/src/HABApp/openhab/connection_handler/http_connection.py", line 269, in start_sse_event_listener
2021-05-06 19:17:15,066[ HABApp.openhab.connection]ERROR| start_sse_event_listener:     async for event in event_source:
2021-05-06 19:17:15,066[ HABApp.openhab.connection]ERROR| start_sse_event_listener:   File "/usr/local/lib/python3.8/dist-packages/aiohttp_sse_client/client.py", line 157, in __anext__
2021-05-06 19:17:15,066[ HABApp.openhab.connection]ERROR| start_sse_event_listener:     async for line_in_bytes in self._response.content:
2021-05-06 19:17:15,067[ HABApp.openhab.connection]ERROR| start_sse_event_listener:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/streams.py", line 39, in __anext__
2021-05-06 19:17:15,067[ HABApp.openhab.connection]ERROR| start_sse_event_listener:     rv = await self.read_func()
2021-05-06 19:17:15,067[ HABApp.openhab.connection]ERROR| start_sse_event_listener:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/streams.py", line 332, in readline
2021-05-06 19:17:15,068[ HABApp.openhab.connection]ERROR| start_sse_event_listener:     raise ValueError("Line is too long")
2021-05-06 19:17:15,068[ HABApp.openhab.connection]ERROR| start_sse_event_listener: ValueError: Line is too long
2021-05-06 19:17:15,068[ HABApp.openhab.connection]WARNI|         set_offline: Disconnected! Uncaught error in process_sse_events: Line is too long
```
i know it's an issue with the sse library, but I thought it was fixed at some point?

**Comment by spacemanspiff2007** [comment]
You can increase the value [here](https://github.com/spacemanspiff2007/HABApp/blob/744b928af1951f5451d07d11dac21bfe3d352723/src/HABApp/openhab/connection_handler/http_connection.py#L247). The current 512k buffer will give you about ~220k image size.

It's a trade off because settings this value very high means that with every message from openhab the specified amount of ram will be allocated, event if it's not necessary. 
With many messages I assume it'll unnecessarily increase ram usage and probably decrease speed.
If it is to small you'll get the line error as above.
Imho the proper way is to put this in the configuration file but I'm not sure yet if it should be another config file for the "internals" of habapp or the one where the folder configuration is make.
What are your ideas?

**Comment by NickWaterton** [comment]
I think it should be in the same configuration file as the folders. That way, you only have the one configuration file to worry about.

The problem is that it’s really guesswork as to what the right value is. Everything works fine, until you pull an image that is too large, then the whole OH connection fails.

Unless you know this is the problem, it’s hard to debug, as you don’t know ahead of time how large an image is being pulled.

So, in addition to being configurable, maybe a more graceful failure, and a suggestion for what the maximum buffer size should be would be a good idea, rather than “line is too long”. I realize most of this is out of your hands, as it’s buried in aiohttp, but it’s worth looking at.

Thanks.

**Comment by spacemanspiff2007** [comment]
Maybe I can catch the exception and re raise a different one with a nicer error message that hints to the configuration option.
I can't prevent the disconnect though 😞 

Hinting at the optimum buffer size is hard, but I think doable.

**Comment by spacemanspiff2007** [comment]
1.0 adds a config option for the buffer
