### ISSUE TITLE
HABApp install fails on clean OpenHABian 1.7.2 install (and 1.7.3)

### ISSUE THREAD

**Issue by magnuslsjoberg** [spacemanspiff2007/HABApp#264]
I had a crash and decided it was time to get a new SD-card and setup OpenHABian from scratch. 
As a coincident OpenHABian 1.7.2 was released today.

After installing HAPApp from openhabian-config, I found that HABApp failed to start due to missing requirements.

```
openhabian@openhabian:~ $ sudo systemctl status habapp
● habapp.service - HABApp
     Loaded: loaded (/etc/systemd/system/habapp.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-01-27 20:39:24 CET; 1h 16min ago
       Docs: https://habapp.readthedocs.io
   Main PID: 695 (code=exited, status=1/FAILURE)
        CPU: 218ms

Jan 27 20:39:24 openhabian habapp[695]: Traceback (most recent call last):
Jan 27 20:39:24 openhabian habapp[695]:   File "/opt/habapp/bin/habapp", line 5, in <module>
Jan 27 20:39:24 openhabian habapp[695]:     from HABApp.__main__ import main
Jan 27 20:39:24 openhabian habapp[695]:   File "/opt/habapp/lib/python3.9/site-packages/HABApp/__init__.py", line 5, in <module>
Jan 27 20:39:24 openhabian habapp[695]:     import HABApp.__do_setup__
Jan 27 20:39:24 openhabian habapp[695]:   File "/opt/habapp/lib/python3.9/site-packages/HABApp/__do_setup__.py", line 4, in <module>
Jan 27 20:39:24 openhabian habapp[695]:     import pydantic  # noqa: E402
Jan 27 20:39:24 openhabian habapp[695]: ModuleNotFoundError: No module named 'pydantic'
Jan 27 20:39:24 openhabian systemd[1]: habapp.service: Main process exited, code=exited, status=1/FAILURE
Jan 27 20:39:24 openhabian systemd[1]: habapp.service: Failed with result 'exit-code'.
```

Very few modules seem to be installed:

```
openhabian@openhabian:~ $ source /opt/habapp/bin/activate
(habapp) openhabian@openhabian:~ $ pip freeze
HABApp==0.31.2
pkg_resources==0.0.0
(habapp) openhabian@openhabian:~ $ 
```

In order of error, I had to install:
```
pydantic
EasyCo
eascheduler
stackprinter
watchdog
paho-mqtt
aiohttp
aiohttp_sse_client
```

Now HABApp starts and I get:
```
(habapp) openhabian@openhabian:~ $ pip freeze
aiohttp==3.8.1
aiohttp-sse-client==0.2.1
aiosignal==1.2.0
astral==2.2
async-timeout==4.0.2
attrs==21.4.0
charset-normalizer==2.0.10
EAScheduler==0.1.4
EasyCo==0.2.3
frozenlist==1.3.0
HABApp==0.31.2
idna==3.3
multidict==6.0.2
paho-mqtt==1.6.1
pendulum==2.1.2
pkg_resources==0.0.0
pydantic==1.9.0
python-dateutil==2.8.2
pytz==2021.3
pytzdata==2020.1
ruamel.yaml==0.17.20
ruamel.yaml.clib==0.2.6
six==1.16.0
stackprinter==0.2.5
typing_extensions==4.0.1
voluptuous==0.12.2
watchdog==2.1.6
yarl==1.7.2
(habapp) openhabian@openhabian:~ $ 
```

**Comment by magnuslsjoberg** [comment]
And after a while(!!??) a few more:

```
immutables
bidict
```

**Comment by spacemanspiff2007** [comment]
What kind of hardware are you running and what version of HABApp is getting installed?
I implemented some logic in 0.31.2 and there is even a debug switch (--debug-info) which will show you all required information.

**Comment by magnuslsjoberg** [comment]
RPi 3 Model B Rev 1.2
HABApp 0.31.2

After my manual installation of the required modules it works fine.

**Comment by magnuslsjoberg** [comment]
```
(habapp) openhabian@openhabian:~ $ habapp --debug-info -c /srv/openhab-conf/habapp/
    __  _____    ____  ___
   / / / /   |  / __ )/   |  ____  ____
  / /_/ / /| | / __  / /| | / __ \/ __ \
/ __  / ___ |/ /_/ / ___ |/ /_/ / /_/ /
/_/ /_/_/  |_/_____/_/  |_/ .___/ .___/
                         /_/   /_/
                                     0.31.2
Debug information
--------------------------------------------------------------------------------
Platform            : Linux-5.10.92-v7+-armv7l-with-glibc2.31
Machine             : armv7l
Python version      : 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]
 
Installed Packages
--------------------------------------------------------------------------------
aiohttp             : 3.8.1
aiohttp-sse-client  : 0.2.1
aiosignal           : 1.2.0
astral              : 2.2
async-timeout       : 4.0.2
attrs               : 21.4.0
bidict              : 0.21.4
bitarray            : 2.3.5
certifi             : 2021.10.8
cffi                : 1.15.0
charset-normalizer  : 2.0.10
cryptography        : 36.0.1
eascheduler         : 0.1.4
easyco              : 0.2.3
frozenlist          : 1.3.0
habapp              : 0.31.2
idna                : 3.3
ifaddr              : 0.1.7
immutables          : 0.16
mediafile           : 0.9.0
miniaudio           : 1.46
multidict           : 6.0.2
mutagen             : 1.45.1
paho-mqtt           : 1.6.1
pendulum            : 2.1.2
pip                 : 21.3.1
pkg-resources       : 0.0.0
protobuf            : 3.19.3
pyatv               : 0.10.0
pycparser           : 2.21
pydantic            : 1.9.0
python-dateutil     : 2.8.2
pytz                : 2021.3
pytzdata            : 2020.1
requests            : 2.27.1
ruamel.yaml         : 0.17.20
ruamel.yaml.clib    : 0.2.6
setuptools          : 60.5.0
six                 : 1.16.0
srptools            : 1.0.1
stackprinter        : 0.2.5
typing-extensions   : 4.0.1
urllib3             : 1.26.8
voluptuous          : 0.12.2
watchdog            : 2.1.6
yarl                : 1.7.2
zeroconf            : 0.38.1
(habapp) openhabian@openhabian:~ $
```

**Comment by magnuslsjoberg** [comment]
No error messages at all during install!

It just didn’t start and when I checked why, I saw the pydantic error above. Then I just picked them one by one.

**Comment by spacemanspiff2007** [comment]
Hm - strange. It should at least display "Error".
Do you have some bash knowledge and could help me with this?

**Comment by magnuslsjoberg** [comment]
By no means a bash expert (after using too many languages it is all a big blur..) but I can give it a try.

What should I test/do?

**Comment by spacemanspiff2007** [comment]
Imho the first step would be trying to reproduce the issue.
E.g. with a fresh installation of habapp (and or openhabian) on dedicated hardware or a vm.
Could check if you just missed the issue or if it was indeed not reported.
Then execute the installation steps manually and try and see where it fails.

**Comment by magnuslsjoberg** [comment]
I finally got the time to update my RPi3 to a RPi4 and installing OpenHABian v1.7.3 from scratch, I get exactly the same behaviour!  

```
openhabian@openhabian:/srv/openhab-conf $ sudo systemctl status habapp
● habapp.service - HABApp
     Loaded: loaded (/etc/systemd/system/habapp.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2022-04-23 20:15:09 CEST; 40min ago
       Docs: https://habapp.readthedocs.io
    Process: 675 ExecStart=/opt/habapp/bin/habapp -c /etc/openhab/habapp (code=exited, status=1/FAILURE)
   Main PID: 675 (code=exited, status=1/FAILURE)
        CPU: 239ms

Apr 23 20:15:09 openhabian habapp[675]: Traceback (most recent call last):
Apr 23 20:15:09 openhabian habapp[675]:   File "/opt/habapp/bin/habapp", line 5, in <module>
Apr 23 20:15:09 openhabian habapp[675]:     from HABApp.__main__ import main
Apr 23 20:15:09 openhabian habapp[675]:   File "/opt/habapp/lib/python3.9/site-packages/HABApp/__init__.py", line 5, in <module>
Apr 23 20:15:09 openhabian habapp[675]:     import HABApp.__do_setup__
Apr 23 20:15:09 openhabian habapp[675]:   File "/opt/habapp/lib/python3.9/site-packages/HABApp/__do_setup__.py", line 4, in <module>
Apr 23 20:15:09 openhabian habapp[675]:     import pydantic  # noqa: E402
Apr 23 20:15:09 openhabian habapp[675]: ModuleNotFoundError: No module named 'pydantic'
Apr 23 20:15:09 openhabian systemd[1]: habapp.service: Main process exited, code=exited, status=1/FAILURE
Apr 23 20:15:09 openhabian systemd[1]: habapp.service: Failed with result 'exit-code'.
openhabian@openhabian:/srv/openhab-conf $ source /opt/habapp/bin/activate
(habapp) openhabian@openhabian:/srv/openhab-conf $ pip freeze
HABApp==0.31.2
pkg_resources==0.0.0
(habapp) openhabian@openhabian:/srv/openhab-conf $ habapp --debug-info -c /srv/openhab-conf/habapp/
Traceback (most recent call last):
  File "/opt/habapp/bin/habapp", line 5, in <module>
    from HABApp.__main__ import main
  File "/opt/habapp/lib/python3.9/site-packages/HABApp/__init__.py", line 5, in <module>
    import HABApp.__do_setup__
  File "/opt/habapp/lib/python3.9/site-packages/HABApp/__do_setup__.py", line 4, in <module>
    import pydantic  # noqa: E402
ModuleNotFoundError: No module named 'pydantic'
(habapp) openhabian@openhabian:/srv/openhab-conf $ 
```

I have not done any manual installation so this would be a good start to troubleshoot.

@spacemanspiff2007 Can you direct me to what I should look into? Any specific logs etc?

Below is the relevant section from the openhabian-config log:

```
2022-04-23_20:11:26_CEST [openHABian] Updating Linux package information... OK
2022-04-23_20:11:26_CEST [openHABian] Installing HABApp prerequisites (dev, venv) ... 
$ apt-get install --yes python3-dev python3-venv 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-dev is already the newest version (3.9.2-3).
The following NEW packages will be installed:
  python3-venv python3.9-venv
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 6,588 B of archives.
After this operation, 33.8 kB of additional disk space will be used.
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf python3-venv armhf 3.9.2-3 [1,188 B]
Get:1 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf python3.9-venv armhf 3.9.2-1+rpi1 [5,400 B]
Fetched 6,588 B in 0s (18.8 kB/s)                       
Selecting previously unselected package python3.9-venv.
(Reading database ... 56329 files and directories currently installed.)
Preparing to unpack .../python3.9-venv_3.9.2-1+rpi1_armhf.deb ...
Unpacking python3.9-venv (3.9.2-1+rpi1) ...
Selecting previously unselected package python3-venv.
Preparing to unpack .../python3-venv_3.9.2-3_armhf.deb ...
Unpacking python3-venv (3.9.2-3) ...
Setting up python3.9-venv (3.9.2-1+rpi1) ...
Setting up python3-venv (3.9.2-3) ...
Updating FireMotD available updates count ... 
OK
2022-04-23_20:11:50_CEST [openHABian] Creating venv ... 
$ cd /opt 

$ python3 -m venv habapp 

$ chown -R openhab:openhabian /opt/habapp 

$ chmod -R 775 /opt/habapp 
OK
2022-04-23_20:12:05_CEST [openHABian] Installing HABApp ... 
$ cd habapp 

$ source bin/activate 

$ python3 -m pip install --upgrade pip setuptools 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pip in ./lib/python3.9/site-packages (20.3.4)
Collecting pip
  Downloading https://www.piwheels.org/simple/pip/pip-22.0.4-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 874 kB/s 
Requirement already satisfied: setuptools in ./lib/python3.9/site-packages (44.1.1)
Collecting setuptools
  Downloading https://www.piwheels.org/simple/setuptools/setuptools-62.1.0-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 916 kB/s 
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 44.1.1
    Uninstalling setuptools-44.1.1:
      Successfully uninstalled setuptools-44.1.1
  Attempting uninstall: pip
    Found existing installation: pip 20.3.4
    Uninstalling pip-20.3.4:
      Successfully uninstalled pip-20.3.4
Successfully installed pip-22.0.4 setuptools-62.1.0

$ python3 -m pip install --upgrade habapp 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting habapp
  Downloading https://www.piwheels.org/simple/habapp/HABApp-0.31.2-py3-none-any.whl (152 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.3/152.3 KB 1.3 MB/s eta 0:00:00
Installing collected packages: habapp
Successfully installed habapp-0.31.2

$ deactivate 
OK
2022-04-23_20:12:52_CEST [openHABian] Creating HABApp configuration folder ... 
$ mkdir -p /etc/openhab/habapp 

$ fix_permissions /etc/openhab/habapp openhab:openhabian 775 775 
OK
2022-04-23_20:12:52_CEST [openHABian] Setting up HABApp as a service ... 
$ systemctl enable --now habapp.service 
Created symlink /etc/systemd/system/multi-user.target.wants/habapp.service → /etc/systemd/system/habapp.service.
OK
2022-04-23_20:13:13_CEST [openHABian] Updating Linux package information... OK
```

**Comment by magnuslsjoberg** [comment]
```
(habapp) openhabian@openhabian:/srv/openhab-conf $ raspinfo 
System Information
------------------

Raspberry Pi 4 Model B Rev 1.5
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"

Raspberry Pi reference 2022-01-28
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, f01430c9d8f67a4b9719cc00e74a2079d3834d5d, stage2

Linux openhabian 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux
Revision	: c03115
Serial		: 100000002491190a
Model		: Raspberry Pi 4 Model B Rev 1.5
Throttled flag  : throttled=0x0
...
```

**Comment by magnuslsjoberg** [comment]
I am no python programmer so I may be on thin ice here, but isn't "Requires-Dist: ..." missing from the HABApp-distinfo/METADATA? (or something related to that...)

```
(habapp) openhabian@openhabian:/opt/habapp $ python3 -m pip install --upgrade habapp
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: habapp in ./lib/python3.9/site-packages (0.31.2)
```

Shouldn't this download all dependencies?

**Comment by magnuslsjoberg** [comment]
If I clone the repo to my MacBook and do a `pip install .`, the following METADATA file is installed:
```
HABApp> cat /usr/local/lib/python3.8/site-packages/HABApp-0.31.2.dist-info/METADATA
Metadata-Version: 2.1
Name: HABApp
Version: 0.31.2
Summary: Easy automation with MQTT and/or openHAB. Create home automation rules in python.
Home-page: https://github.com/spacemanspiff2007/HABApp
Author: spaceman_spiff
License: UNKNOWN
Project-URL: Documentation, https://habapp.readthedocs.io/
Project-URL: GitHub, https://github.com/spacemanspiff2007/HABApp
Keywords: mqtt,openhab,habapp,home automation
Platform: UNKNOWN
Classifier: Development Status :: 4 - Beta
Classifier: Framework :: AsyncIO
Classifier: License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
Classifier: Operating System :: OS Independent
Classifier: Programming Language :: Python :: 3.7
Classifier: Programming Language :: Python :: 3.8
Classifier: Programming Language :: Python :: 3.9
Classifier: Programming Language :: Python :: 3 :: Only
Classifier: Topic :: Home Automation
Requires-Python: >=3.7
Description-Content-Type: text/markdown
License-File: LICENSE
Requires-Dist: aiohttp-sse-client (==0.2.1)
Requires-Dist: aiohttp (==3.8.1)
Requires-Dist: bidict (==0.21.4)
Requires-Dist: eascheduler (==0.1.4)
Requires-Dist: easyco (==0.2.3)
Requires-Dist: paho-mqtt (==1.6.1)
Requires-Dist: pydantic (==1.8.2)
Requires-Dist: stackprinter (==0.2.5)
Requires-Dist: voluptuous (==0.12.2)
Requires-Dist: watchdog (==2.1.6)
Requires-Dist: ujson (==4.3.0)
Requires-Dist: immutables (==0.16)
Requires-Dist: pendulum (==2.1.2)
```

The metadata file in the OpenHABian looks like this:
```
openhabian@openhabian:~ $ cat /opt/habapp/lib/python3.9/site-packages/HABApp-0.31.2.dist-info/METADATA 
Metadata-Version: 2.1
Name: HABApp
Version: 0.31.2
Summary: Easy automation with MQTT and/or openHAB. Create home automation rules in python.
Home-page: https://github.com/spacemanspiff2007/HABApp
Author: spaceman_spiff
License: UNKNOWN
Project-URL: Documentation, https://habapp.readthedocs.io/
Project-URL: GitHub, https://github.com/spacemanspiff2007/HABApp
Keywords: mqtt,openhab,habapp,home automation
Platform: UNKNOWN
Classifier: Development Status :: 4 - Beta
Classifier: Framework :: AsyncIO
Classifier: License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
Classifier: Operating System :: OS Independent
Classifier: Programming Language :: Python :: 3.7
Classifier: Programming Language :: Python :: 3.8
Classifier: Programming Language :: Python :: 3.9
Classifier: Programming Language :: Python :: 3 :: Only
Classifier: Topic :: Home Automation
Requires-Python: >=3.7
Description-Content-Type: text/markdown
License-File: LICENSE

UNKNOWN
```

**Comment by spacemanspiff2007** [comment]
Thank you for you detailed analysis. I already suspected something was wrong with the dependency packages.

I guess if you do a pip install on your mackbook the dependencies look the same.
I've already implemented a fix in the dev branch and will make sure to check the METADATA before the next release.
It was not clear to me how to check the dependencies so thank you for showing me how!

**Comment by spacemanspiff2007** [comment]
Setup issue should be fixed with 1.0. Could you check if the metadata is properly set?

**Comment by spacemanspiff2007** [comment]
Ping @magnuslsjoberg

**Comment by magnuslsjoberg** [comment]
I have a spare RPi so I will try to test tonight!

**Comment by magnuslsjoberg** [comment]
Well, took a few more days but I hav now mad a clean install of opanHABian v1.7.4b.
After installation I immediately run openhabian-config to install HABApp.

### First start
First I got some problems with permissions:
```
openhabian@openhabian:~ $ cat  /var/log/openhab/HABApp.log 
2022-09-03 20:44:28.563 [INFO ] [HABApp                              ] - HABApp Version 1.0.4
2022-09-03 20:44:29.114 [WARN ] [HABApp.Config                       ] - Folder for rules files does not exist: rules
2022-09-03 20:44:34.385 [ERROR] [HABApp                              ] - Error [Errno 13] Permission denied: 'rules' in Runtime.start:
2022-09-03 20:44:34.388 [ERROR] [HABApp                              ] - File "/opt/habapp/lib/python3.9/site-packages/HABApp/runtime/runtime.py", line 40 in start
2022-09-03 20:44:34.388 [ERROR] [HABApp                              ] - --------------------------------------------------------------------------------
2022-09-03 20:44:34.389 [ERROR] [HABApp                              ] -      29 | async def start(self, config_folder: Path):
2022-09-03 20:44:34.389 [ERROR] [HABApp                              ] -       (...)
2022-09-03 20:44:34.390 [ERROR] [HABApp                              ] -      36 |         # Start Folder watcher!
2022-09-03 20:44:34.390 [ERROR] [HABApp                              ] -      37 |         HABApp.core.files.watcher.start()
2022-09-03 20:44:34.391 [ERROR] [HABApp                              ] -      39 |         # Load config
2022-09-03 20:44:34.391 [ERROR] [HABApp                              ] - -->  40 |         HABApp.config.load_config(config_folder)
2022-09-03 20:44:34.391 [ERROR] [HABApp                              ] -      42 |         # replace proxy objects
2022-09-03 20:44:34.392 [ERROR] [HABApp                              ] -    ------------------------------------------------------------
2022-09-03 20:44:34.392 [ERROR] [HABApp                              ] -      HABApp.core.EventBus = <HABApp.core.internals.proxy.proxy_obj.ConstProxyObj object at 0x74e46f58>
2022-09-03 20:44:34.393 [ERROR] [HABApp                              ] -      HABApp.core.Items = <HABApp.core.internals.proxy.proxy_obj.ConstProxyObj object at 0x75caa2f8>
2022-09-03 20:44:34.393 [ERROR] [HABApp                              ] -      self = <HABApp.runtime.runtime.Runtime object at 0x74c70058>
2022-09-03 20:44:34.393 [ERROR] [HABApp                              ] -      self.rule_manager = None
2022-09-03 20:44:34.394 [ERROR] [HABApp                              ] -      async_context = <ContextVar name='async_ctx' at 0x74e604c0>
2022-09-03 20:44:34.394 [ERROR] [HABApp                              ] -      config_folder = PosixPath('/etc/openhab/habapp')
2022-09-03 20:44:34.395 [ERROR] [HABApp                              ] -      e = PermissionError(13, 'Permission denied')
2022-09-03 20:44:34.395 [ERROR] [HABApp                              ] -      token = <Token var=<ContextVar name='async_ctx' at 0x74e604c0> at 0x74bccec8>
2022-09-03 20:44:34.396 [ERROR] [HABApp                              ] -    ------------------------------------------------------------
2022-09-03 20:44:34.396 [ERROR] [HABApp                              ] - 
2022-09-03 20:44:34.396 [ERROR] [HABApp                              ] - File "/opt/habapp/lib/python3.9/site-packages/HABApp/config/loader.py", line 36 in load_config
2022-09-03 20:44:34.397 [ERROR] [HABApp                              ] - --------------------------------------------------------------------------------
2022-09-03 20:44:34.397 [ERROR] [HABApp                              ] -      20 | def load_config(config_folder: Path):
2022-09-03 20:44:34.398 [ERROR] [HABApp                              ] -       (...)
2022-09-03 20:44:34.398 [ERROR] [HABApp                              ] -      32 |         loaded_logging = True
2022-09-03 20:44:34.398 [ERROR] [HABApp                              ] -      33 |     except (AbsolutePathExpected, InvalidConfigError):
2022-09-03 20:44:34.399 [ERROR] [HABApp                              ] -      34 |         pass
2022-09-03 20:44:34.399 [ERROR] [HABApp                              ] - -->  36 |     load_habapp_cfg(do_print=not loaded_logging)
2022-09-03 20:44:34.400 [ERROR] [HABApp                              ] -      38 |     if not loaded_logging:
2022-09-03 20:44:34.400 [ERROR] [HABApp                              ] -    ------------------------------------------------------------
2022-09-03 20:44:34.401 [ERROR] [HABApp                              ] -      (AbsolutePathExpected, InvalidConfigError) = (<class 'HABApp.config.errors.AbsolutePathExpected'>, <class 'HABApp.config.errors.InvalidConfigError'>)
2022-09-03 20:44:34.401 [ERROR] [HABApp                              ] -      config_folder = PosixPath('/etc/openhab/habapp')
2022-09-03 20:44:34.402 [ERROR] [HABApp                              ] -      loaded_logging = True
2022-09-03 20:44:34.402 [ERROR] [HABApp                              ] -      logging_cfg_path = PosixPath('/etc/openhab/habapp/logging.yml')
2022-09-03 20:44:34.402 [ERROR] [HABApp                              ] -      not loaded_logging = False
2022-09-03 20:44:34.403 [ERROR] [HABApp                              ] -    ------------------------------------------------------------
2022-09-03 20:44:34.403 [ERROR] [HABApp                              ] - 
2022-09-03 20:44:34.404 [ERROR] [HABApp                              ] - File "/opt/habapp/lib/python3.9/site-packages/HABApp/config/loader.py", line 79 in load_habapp_cfg
2022-09-03 20:44:34.404 [ERROR] [HABApp                              ] - --------------------------------------------------------------------------------
2022-09-03 20:44:34.404 [ERROR] [HABApp                              ] -      64 | def load_habapp_cfg(do_print=False):
2022-09-03 20:44:34.405 [ERROR] [HABApp                              ] -       (...)
2022-09-03 20:44:34.405 [ERROR] [HABApp                              ] -      75 |     # check if folders exist and print warnings, maybe because of missing permissions
2022-09-03 20:44:34.406 [ERROR] [HABApp                              ] -      76 |     if not CONFIG.directories.rules.is_dir():
2022-09-03 20:44:34.406 [ERROR] [HABApp                              ] -      77 |         log.warning(f'Folder for rules files does not exist: {CONFIG.directories.rules}')
2022-09-03 20:44:34.407 [ERROR] [HABApp                              ] - -->  79 |     CONFIG.directories.create_folders()
2022-09-03 20:44:34.407 [ERROR] [HABApp                              ] -      81 |     log.debug(f'Local Timezone: {eascheduler.const.local_tz}')
2022-09-03 20:44:34.407 [ERROR] [HABApp                              ] -    ------------------------------------------------------------
2022-09-03 20:44:34.408 [ERROR] [HABApp                              ] -      CONFIG.directories.rules = PosixPath('rules')
2022-09-03 20:44:34.408 [ERROR] [HABApp                              ] -      do_print = False
2022-09-03 20:44:34.409 [ERROR] [HABApp                              ] -      log = <Logger HABApp.Config (INFO)>
2022-09-03 20:44:34.409 [ERROR] [HABApp                              ] -    ------------------------------------------------------------
2022-09-03 20:44:34.409 [ERROR] [HABApp                              ] - 
2022-09-03 20:44:34.410 [ERROR] [HABApp                              ] - File "/opt/habapp/lib/python3.9/site-packages/HABApp/config/models/directories.py", line 49 in create_folders
2022-09-03 20:44:34.410 [ERROR] [HABApp                              ] - --------------------------------------------------------------------------------
2022-09-03 20:44:34.411 [ERROR] [HABApp                              ] -      45 | def create_folders(self):
2022-09-03 20:44:34.411 [ERROR] [HABApp                              ] -      46 | 
2022-09-03 20:44:34.412 [ERROR] [HABApp                              ] -      47 |     # create folder structure if it does not exist
2022-09-03 20:44:34.412 [ERROR] [HABApp                              ] -      48 |     if not self.rules.is_dir():
2022-09-03 20:44:34.412 [ERROR] [HABApp                              ] - -->  49 |         self.rules.mkdir()
2022-09-03 20:44:34.413 [ERROR] [HABApp                              ] -      50 |     if not self.logging.is_dir():
2022-09-03 20:44:34.413 [ERROR] [HABApp                              ] -    ------------------------------------------------------------
2022-09-03 20:44:34.414 [ERROR] [HABApp                              ] -      self.config = PosixPath('config')
2022-09-03 20:44:34.414 [ERROR] [HABApp                              ] -      self.lib = PosixPath('lib')
2022-09-03 20:44:34.415 [ERROR] [HABApp                              ] -      self.logging = PosixPath('/var/log/openhab')
2022-09-03 20:44:34.415 [ERROR] [HABApp                              ] -      self.param = PosixPath('params')
2022-09-03 20:44:34.415 [ERROR] [HABApp                              ] -      self.rules = PosixPath('rules')
2022-09-03 20:44:34.416 [ERROR] [HABApp                              ] -      sys.path = ['/opt/habapp/bin', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/opt/habapp/lib/python3.9/site-packages']
2022-09-03 20:44:34.416 [ERROR] [HABApp                              ] -      log = <Logger HABApp.Config (INFO)>
2022-09-03 20:44:34.417 [ERROR] [HABApp                              ] -      self.lib is not None = True
2022-09-03 20:44:34.417 [ERROR] [HABApp                              ] -    ------------------------------------------------------------
2022-09-03 20:44:34.417 [ERROR] [HABApp                              ] - 
2022-09-03 20:44:34.418 [ERROR] [HABApp                              ] - File "/usr/lib/python3.9/pathlib.py", line 1312 in mkdir
2022-09-03 20:44:34.418 [ERROR] [HABApp                              ] - --------------------------------------------------------------------------------
2022-09-03 20:44:34.419 [ERROR] [HABApp                              ] -      1307 | def mkdir(self, mode=0o777, parents=False, exist_ok=False):
2022-09-03 20:44:34.419 [ERROR] [HABApp                              ] -      1308 |     """
2022-09-03 20:44:34.420 [ERROR] [HABApp                              ] -      1309 |     Create a new directory at this given path.
2022-09-03 20:44:34.420 [ERROR] [HABApp                              ] -      1310 |     """
2022-09-03 20:44:34.420 [ERROR] [HABApp                              ] -      1311 |     try:
2022-09-03 20:44:34.421 [ERROR] [HABApp                              ] - -->  1312 |         self._accessor.mkdir(self, mode)
2022-09-03 20:44:34.421 [ERROR] [HABApp                              ] -      1313 |     except FileNotFoundError:
2022-09-03 20:44:34.422 [ERROR] [HABApp                              ] -    ------------------------------------------------------------
2022-09-03 20:44:34.422 [ERROR] [HABApp                              ] -      not exist_ok or not self.is_dir() = True
2022-09-03 20:44:34.422 [ERROR] [HABApp                              ] -      not parents or self.parent == self = True
2022-09-03 20:44:34.423 [ERROR] [HABApp                              ] -      self = PosixPath('rules')
2022-09-03 20:44:34.423 [ERROR] [HABApp                              ] -      self._accessor = <pathlib._NormalAccessor object at 0x75e2d640>
2022-09-03 20:44:34.424 [ERROR] [HABApp                              ] -      exist_ok = False
2022-09-03 20:44:34.424 [ERROR] [HABApp                              ] -      mode = 511
2022-09-03 20:44:34.425 [ERROR] [HABApp                              ] -      not exist_ok = True
2022-09-03 20:44:34.425 [ERROR] [HABApp                              ] -      not parents = True
2022-09-03 20:44:34.425 [ERROR] [HABApp                              ] -      parents = False
2022-09-03 20:44:34.426 [ERROR] [HABApp                              ] -    ------------------------------------------------------------
2022-09-03 20:44:34.426 [ERROR] [HABApp                              ] - 
2022-09-03 20:44:34.427 [ERROR] [HABApp                              ] - --------------------------------------------------------------------------------
2022-09-03 20:44:34.427 [ERROR] [HABApp                              ] - Traceback (most recent call last):
2022-09-03 20:44:34.427 [ERROR] [HABApp                              ] -   File "/opt/habapp/lib/python3.9/site-packages/HABApp/runtime/runtime.py", line 40, in start
2022-09-03 20:44:34.428 [ERROR] [HABApp                              ] -     HABApp.config.load_config(config_folder)
2022-09-03 20:44:34.428 [ERROR] [HABApp                              ] -   File "/opt/habapp/lib/python3.9/site-packages/HABApp/config/loader.py", line 36, in load_config
2022-09-03 20:44:34.429 [ERROR] [HABApp                              ] -     load_habapp_cfg(do_print=not loaded_logging)
2022-09-03 20:44:34.429 [ERROR] [HABApp                              ] -   File "/opt/habapp/lib/python3.9/site-packages/HABApp/config/loader.py", line 79, in load_habapp_cfg
2022-09-03 20:44:34.430 [ERROR] [HABApp                              ] -     CONFIG.directories.create_folders()
2022-09-03 20:44:34.430 [ERROR] [HABApp                              ] -   File "/opt/habapp/lib/python3.9/site-packages/HABApp/config/models/directories.py", line 49, in create_folders
2022-09-03 20:44:34.430 [ERROR] [HABApp                              ] -     self.rules.mkdir()
2022-09-03 20:44:34.431 [ERROR] [HABApp                              ] -   File "/usr/lib/python3.9/pathlib.py", line 1312, in mkdir
2022-09-03 20:44:34.431 [ERROR] [HABApp                              ] -     self._accessor.mkdir(self, mode)
2022-09-03 20:44:34.432 [ERROR] [HABApp                              ] - PermissionError: [Errno 13] Permission denied: 'rules'
```

### Permissions
I then run "Fix Permissions" in openhabian-config and restarted HABApp.

After that HABApp will start and log `2022-09-03 20:51:36.833 [WARN ] [HABApp.openhab.connection           ] - Status 401 for GET http://localhost:8080/rest/systeminfo` once a second.

### openHAB setup
Since openHAB wasn't set up, I added an admin user and activated basic authentication.
I also entered user and pass in config.yml and set `verify_ssl` to false.

### Restart of HABApp
After HABApp was restarted, I instead get following logs:
`2022-09-03 21:00:12.282 [WARN ] [HABApp.openhab.connection           ] - Status 404 for PUT http://localhost:8080/rest/items/HABApp_Ping/state NULL`

I don't know when or how HABApp_Ping is supposed to be created, but at this stage, I rebooted the RPi completely.

### After reboot of RPi
Still a 404 for HABApp_Ping. I will ignore this for now and install some binding in openHAB.

### Installing openHAB Network binding
Installed Network Binding via GUI and rebooted... and no Things show up... (I haven't created any Things in ages and use all text files for my real setup). OK, so I use one of my text fi8les from my real setup instead...

### Installing an .items file...
Well, since HAPApp_Ping is missing, perhaps I create that one...

### Finally, OK!
In HABApp.log: 
```
2022-09-03 21:47:29.497 [INFO ] [HABApp.Rules                        ] - Added rule "Ping" from rules/HABApp_Ping.py
2022-09-03 21:47:29.501 [INFO ] [HABApp.Ping                         ] - in Ping!!!!
```
and in events.log:
```
2022-09-03 21:49:40.664 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'HABApp_Ping' changed from 46.5 to 44.2
```

### CONCLUSION: HAPApp installs (almost) properly on openHABian v1.7.4b

I think it is OK to close this one but permissions and `HABAPP_Ping` may still be minor issues that could be improved.

**Comment by spacemanspiff2007** [comment]
Imho all issues are addressed. If you stumble over anything again feel free to open an issue again.
