### ISSUE TITLE
Docker container always terminates on Synology

### ISSUE THREAD

**Issue by nanosonde** [spacemanspiff2007/HABApp#29]
Hi!
I am running HABapp on my docker host which is a Synology DS918+ NAS.
HABapp successfully created the config files in the config files.

However, even with two demo rules in the config folder the container terminates immediately.

The log files shows:
```
[2019-04-19 08:07:19,046] [                   HABApp]     INFO | HABApp Version 0.4.0
[2019-04-19 08:07:19,047] [   HABApp.mqtt.connection]     INFO | MQTT disabled
[2019-04-19 08:07:19,057] [                   HABApp]    ERROR | Traceback (most recent call last):
[2019-04-19 08:07:19,058] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.7/site-packages/HABApp/__main__.py", line 71, in main
[2019-04-19 08:07:19,058] [                   HABApp]    ERROR |     app = HABApp.Runtime(find_config_folder())
[2019-04-19 08:07:19,058] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.7/site-packages/HABApp/runtime/runtime.py", line 31, in __init__
[2019-04-19 08:07:19,058] [                   HABApp]    ERROR |     self.rule_manager = HABApp.rule_manager.RuleManager(self)
[2019-04-19 08:07:19,059] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.7/site-packages/HABApp/rule_manager/rule_manager.py", line 46, in __init__
[2019-04-19 08:07:19,059] [                   HABApp]    ERROR |     watch_subfolders=True
[2019-04-19 08:07:19,059] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.7/site-packages/HABApp/runtime/folder_watcher/folder_watcher.py", line 36, in watch_folder
[2019-04-19 08:07:19,059] [                   HABApp]    ERROR |     assert folder.is_dir()
[2019-04-19 08:07:19,060] [                   HABApp]    ERROR | AssertionError
```

Any idea what's wrong?
The config dir seems to be available readable and writable.

![grafik](https://user-images.githubusercontent.com/2073569/56414906-5dca6700-628c-11e9-9d11-cad95e44e378.png)

**Comment by spacemanspiff2007** [comment]
Can you check the config.yml what kind of folder is configured?
Normally it is "rules", so can you try and create a folder (parallel to log) and move the files there?

**Comment by spacemanspiff2007** [comment]
Sorry, I closed this on accident. Did creating the "rules" folder resolve your problem?

**Comment by nanosonde** [comment]
Yes, creating the "rules" folder  solved it. Thanks!
