### ISSUE TITLE
SSE request Error: Unknown Event: GroupItemStateChangedEvent

### ISSUE THREAD

**Issue by nanosonde** [spacemanspiff2007/HABApp#32]
I have seen this in the logs:
```
[2019-04-19 09:27:09,556] [                   HABApp]     INFO | HABApp Version 0.4.0
[2019-04-19 09:27:09,556] [   HABApp.mqtt.connection]     INFO | MQTT disabled
[2019-04-19 09:27:09,558] [    HABApp.RuleParameters]     INFO | Parameter files disabled. Folder /config/param does not exist!
[2019-04-19 09:27:09,587] [HABApp.openhab.connection]     INFO | Connected to OpenHAB instance 5b13f244-c394-47c1-aa36-3eec75f368ee
[2019-04-19 09:27:09,645] [HABApp.openhab.Connection]     INFO | Updated 154 items
[2019-04-19 09:27:15,066] [             HABApp.Rules]     INFO | Added rule "MyRule" from time_rule.py
[2019-04-19 09:27:15,567] [             HABApp.Rules]     INFO | Added rule "MyOpenhabRule" from openhab_rule.py
[2019-04-19 09:27:15,568] [              HABApp.Rule]  WARNING | Item "TestContact" does not exist (yet)! self.listen_event in "MyOpenhabRule" may not work as intended.
[2019-04-19 09:27:15,568] [              HABApp.Rule]  WARNING | Item "TestDateTime" does not exist (yet)! self.listen_event in "MyOpenhabRule" may not work as intended.
[2019-04-19 09:27:15,568] [              HABApp.Rule]  WARNING | Item "TestDateTime" does not exist (yet)! self.listen_event in "MyOpenhabRule" may not work as intended.
[2019-04-19 09:27:15,568] [              HABApp.Rule]  WARNING | Item "TestSwitch" does not exist (yet)! self.listen_event in "MyOpenhabRule" may not work as intended.
[2019-04-19 09:27:15,568] [              HABApp.Rule]  WARNING | Item "TestSwitch" does not exist (yet)! self.listen_event in "MyOpenhabRule" may not work as intended.
[2019-04-19 09:27:44,188] [HABApp.openhab.connection]    ERROR | SSE request Error: Unknown Event: GroupItemStateChangedEvent
[2019-04-19 09:27:44,189] [HABApp.openhab.connection]    ERROR | Traceback (most recent call last):
[2019-04-19 09:27:44,189] [HABApp.openhab.connection]    ERROR |   File "/usr/local/lib/python3.7/site-packages/HABApp/openhab/events/__init__.py", line 14, in get_event
[2019-04-19 09:27:44,190] [HABApp.openhab.connection]    ERROR |     return __event_lookup[event_type](_in_dict)
[2019-04-19 09:27:44,190] [HABApp.openhab.connection]    ERROR | KeyError: 'GroupItemStateChangedEvent'
[2019-04-19 09:27:44,190] [HABApp.openhab.connection]    ERROR | 
[2019-04-19 09:27:44,190] [HABApp.openhab.connection]    ERROR | During handling of the above exception, another exception occurred:
[2019-04-19 09:27:44,190] [HABApp.openhab.connection]    ERROR | 
[2019-04-19 09:27:44,190] [HABApp.openhab.connection]    ERROR | Traceback (most recent call last):
[2019-04-19 09:27:44,191] [HABApp.openhab.connection]    ERROR |   File "/usr/local/lib/python3.7/site-packages/HABApp/openhab/http_connection.py", line 198, in async_process_sse_events
[2019-04-19 09:27:44,191] [HABApp.openhab.connection]    ERROR |     call(event)
[2019-04-19 09:27:44,191] [HABApp.openhab.connection]    ERROR |   File "/usr/local/lib/python3.7/site-packages/HABApp/openhab/oh_connection.py", line 99, in on_sse_event
[2019-04-19 09:27:44,191] [HABApp.openhab.connection]    ERROR |     event = get_event(event)
[2019-04-19 09:27:44,191] [HABApp.openhab.connection]    ERROR |   File "/usr/local/lib/python3.7/site-packages/HABApp/openhab/events/__init__.py", line 16, in get_event
[2019-04-19 09:27:44,191] [HABApp.openhab.connection]    ERROR |     raise ValueError(f'Unknown Event: {event_type:s}')
[2019-04-19 09:27:44,192] [HABApp.openhab.connection]    ERROR | ValueError: Unknown Event: GroupItemStateChangedEvent
```

Where does this error about the unknown event come from?

**Comment by spacemanspiff2007** [comment]
I suspect you are using [group states](https://www.openhab.org/docs/configuration/items.html#group-type-and-state) in your config and I have not yet implemented these.
-.-

**Comment by nanosonde** [comment]
I have used OpenHAB HomeBuilder to generate my initial config.
It makes use of those by default.

```
Group:Switch:OR(ON, OFF)           gLight         "Licht"              <light>           (Home)
Group:Number:AVG                   gTemperature   "Temperatur"         <temperature>     (Home)
Group:Number:AVG                   gHumidity      "Luftfeuchtigkeit"   <humidity>        (Home)
Group:Number:AVG                   gPressure      "Luftdruck"          <pressure>        (Home)
Group:Rollershutter:OR(UP, DOWN)   gShutter       "Rolladen"           <rollershutter>   (Home)
Group:Contact:OR(OPEN, CLOSED)     gWindow        "Fenster"            <window>          (Home)
Group:Number:AVG                   gHeating       "Heizung"            <heating>         (Home)
Group:Switch:OR(ON, OFF)           gMotion        "Bewegungsmelder"    <motion>          (Home)
Group:Contact:OR(OPEN, CLOSED)     gDoor          "Tür"                <door>            (Home)
Group:Dimmer                       gBlind         "Jalousie"           <blinds>          (Home)
Group:Switch:OR(ON, OFF)           gPower         "Steckdose"          <poweroutlet>     (Home)
```

Can I ignore unimplemented items somehow?

**Comment by spacemanspiff2007** [comment]
Sure - just remove everything after ```Group```.
e.g. 
```Group:Switch:OR(ON, OFF)``` with ```Group```
I'll implement the groups next week :+1:

**Comment by spacemanspiff2007** [comment]
I created the missing GroupItemStateChangedEvent class and added lots of documentation.

@nanosonde : It would also be very nice to get some general feedback to HABApp (maybe in the forum or however you like).

**Comment by nanosonde** [comment]
Which forum do you mean?

**Comment by spacemanspiff2007** [comment]
https://community.openhab.org/t/habapp-easy-automation-with-openhab/59669/1
