### ISSUE TITLE
ValueError: Chunk too big

### ISSUE THREAD

**Issue by spacemanspiff2007** [spacemanspiff2007/HABApp#352]
I have a new issue which could be related to the changes of the topic filter.

```
2022-12-30 18:30:47.753 [ERROR] [HABApp.openhab.connection] - SSE request Error: Chunk too big
2022-12-30 18:30:47.757 [ERROR] [HABApp.openhab.connection] - Traceback (most recent call last):
2022-12-30 18:30:47.760 [ERROR] [HABApp.openhab.connection] -   File "/opt/habapp/lib/python3.9/site-packages/HABApp/openhab/connection_handler/http_connection.py", line 228, in start_sse_event_listener
2022-12-30 18:30:47.763 [ERROR] [HABApp.openhab.connection] -     async for event in event_source:
2022-12-30 18:30:47.764 [ERROR] [HABApp.openhab.connection] -   File "/opt/habapp/lib/python3.9/site-packages/aiohttp_sse_client/client.py", line 157, in __anext__
2022-12-30 18:30:47.766 [ERROR] [HABApp.openhab.connection] -     async for line_in_bytes in self._response.content:
2022-12-30 18:30:47.767 [ERROR] [HABApp.openhab.connection] -   File "/opt/habapp/lib/python3.9/site-packages/aiohttp/streams.py", line 35, in __anext__
2022-12-30 18:30:47.767 [ERROR] [HABApp.openhab.connection] -     rv = await self.read_func()
2022-12-30 18:30:47.768 [ERROR] [HABApp.openhab.connection] -   File "/opt/habapp/lib/python3.9/site-packages/aiohttp/streams.py", line 311, in readline
2022-12-30 18:30:47.769 [ERROR] [HABApp.openhab.connection] -     return await self.readuntil()
2022-12-30 18:30:47.770 [ERROR] [HABApp.openhab.connection] -   File "/opt/habapp/lib/python3.9/site-packages/aiohttp/streams.py", line 337, in readuntil
2022-12-30 18:30:47.771 [ERROR] [HABApp.openhab.connection] -     raise ValueError("Chunk too big")
2022-12-30 18:30:47.772 [ERROR] [HABApp.openhab.connection] - ValueError: Chunk too big
2022-12-30 18:30:47.772 [WARN ] [HABApp.openhab.connection] - Disconnected! Uncaught error in process_sse_events: Chunk too big
2022-12-30 18:31:20.017 [INFO ] [HABApp.openhab.connection] - Connected to OpenHAB version 3.4.0 (Release Build)
2022-12-30 18:31:21.506 [INFO ] [HABApp.openhab.items] - Updated 810 Items
2022-12-30 18:31:21.936 [INFO ] [HABApp.openhab.items] - Updated 20 Things
```

I have two servers, where one is my test machine, connected to the main machine with the remote openhab binding.
When I import a new/modified item file to my main machine, I get these errors on my test machine.

_Originally posted by @UrsusS in https://github.com/spacemanspiff2007/HABApp/issues/348#issuecomment-1368027590_

**Comment by spacemanspiff2007** [comment]
Same as [ValueError: Line is too long](https://habapp.readthedocs.io/en/latest/troubleshooting.html#valueerror-line-is-too-long).

--> Docs update
