### ISSUE TITLE
Investigate issue where traceback fails during removing of the event listener

### ISSUE THREAD

**Issue by spacemanspiff2007** [spacemanspiff2007/HABApp#447]
```
2024-05-03 10:08:42.369 [ERROR] [HABApp.Rule] - File "/opt/habapp/lib/python3.11/site-packages/HABApp/core/internals/event_bus_listener.py", line 49 in describe
2024-05-03 10:08:42.369 [ERROR] [HABApp.Rule] - --------------------------------------------------------------------------------
2024-05-03 10:08:42.369 [ERROR] [HABApp.Rule] -      48 | def describe(self) -> str:
2024-05-03 10:08:42.369 [ERROR] [HABApp.Rule] - -->  49 |     return f'"{self.topic}" (filter={self.filter.describe()})'
2024-05-03 10:08:42.369 [ERROR] [HABApp.Rule] -    ------------------------------------------------------------
2024-05-03 10:08:42.369 [ERROR] [HABApp.Rule] -      self = <HABApp.core.internals.event_bus_listener.ContextBoundEventBusListener object at 0x7f2750327fd0>
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] - Error "__str__ returned non-string (type float)" in unload_rule:
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] - Error while formatting traceback: __str__ returned non-string (type float)
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] - Traceback (most recent call last):
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] -   File "/opt/habapp/lib/python3.11/site-packages/HABApp/rule_ctx/rule_ctx.py", line 43, in unload_rule
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] -     to_cancel.cancel()
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] -   File "/opt/habapp/lib/python3.11/site-packages/HABApp/core/internals/event_bus_listener.py", line 57, in cancel
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] -     self._ctx_unlink()
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] -   File "/opt/habapp/lib/python3.11/site-packages/HABApp/core/internals/event_bus_listener.py", line 52, in _ctx_unlink
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] -     event_bus.remove_listener(self)
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] -   File "/opt/habapp/lib/python3.11/site-packages/HABApp/core/internals/event_bus/event_bus.py", line 76, in remove_listener
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] -     habapp_log.warning(f'Event listener for {listener.describe()} has already been removed!')
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] -                     ^^^^^^^^^^^^^^^^^^^
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] -   File "/opt/habapp/lib/python3.11/site-packages/HABApp/core/internals/event_bus_listener.py", line 49, in describe
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] -     return f'"{self.topic}" (filter={self.filter.describe()})'
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] -             ^^^^^^^^^^^^^^^^^^^^^^
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] -   File "/opt/habapp/lib/python3.11/site-packages/HABApp/core/events/filter/event.py", line 64, in describe
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] -     values += f', {self.attr_name1}={self.attr_value1}'
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] -               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-03 10:08:42.375 [ERROR] [HABApp.Rule] - TypeError: __str__ returned non-string (type float)
```

**Comment by spacemanspiff2007** [comment]
Fixed in 24.08.0
