### ISSUE TITLE
Error Unknown Event: ItemTimeSeriesEvent

### ISSUE THREAD

**Issue by silentsimmal** [spacemanspiff2007/HABApp#449]
Hi,
since updateing openHab to the latest release, I get this error quite often (once a minute), therefore my habapp logfile grows very fast always containing the error message below this text.
It seems that there's been a similar issue some time ago, which is already fixed:
https://github.com/spacemanspiff2007/HABApp/issues/437
BR

[2024-07-16 07:51:01,010] [                   HABApp]    ERROR | Error Unknown Event: ItemTimeSeriesEvent for {'topic': 'openhab/items/Tibber_CurrentTotal/timeseries', 'payload': '{"timeSeries":[{"type":"Decimal","value":"0.2736","timestamp":"2024-07-15T22:00:00Z"},{"type":"Decimal","value":"0.2583","timestamp":"2024-07-15T23:00:00Z"},{"type":"Decimal","value":"0.2449","timestamp":"2024-07-16T00:00:00Z"},{"type":"Decimal","value":"0.2263","timestamp":"2024-07-16T01:00:00Z"},{"type":"Decimal","value":"0.2278","timestamp":"2024-07-16T02:00:00Z"},{"type":"Decimal","value":"0.2423","timestamp":"2024-07-16T03:00:00Z"},{"type":"Decimal","value":"0.2781","timestamp":"2024-07-16T04:00:00Z"},{"type":"Decimal","value":"0.2907","timestamp":"2024-07-16T05:00:00Z"},{"type":"Decimal","value":"0.2828","timestamp":"2024-07-16T06:00:00Z"},{"type":"Decimal","value":"0.2571","timestamp":"2024-07-16T07:00:00Z"},{"type":"Decimal","value":"0.208","timestamp":"2024-07-16T08:00:00Z"},{"type":"Decimal","value":"0.1825","timestamp":"2024-07-16T09:00:00Z"},{"type":"Decimal","value":"0.1729","timestamp":"2024-07-16T10:00:00Z"},{"type":"Decimal","value":"0.1693","timestamp":"2024-07-16T11:00:00Z"},{"type":"Decimal","value":"0.1688","timestamp":"2024-07-16T12:00:00Z"},{"type":"Decimal","value":"0.1692","timestamp":"2024-07-16T13:00:00Z"},{"type":"Decimal","value":"0.1797","timestamp":"2024-07-16T14:00:00Z"},{"type":"Decimal","value":"0.2088","timestamp":"2024-07-16T15:00:00Z"},{"type":"Decimal","value":"0.2574","timestamp":"2024-07-16T16:00:00Z"},{"type":"Decimal","value":"0.28","timestamp":"2024-07-16T17:00:00Z"},{"type":"Decimal","value":"0.3271","timestamp":"2024-07-16T18:00:00Z"},{"type":"Decimal","value":"0.3184","timestamp":"2024-07-16T19:00:00Z"},{"type":"Decimal","value":"0.3084","timestamp":"2024-07-16T20:00:00Z"},{"type":"Decimal","value":"0.2828","timestamp":"2024-07-16T21:00:00Z"}],"policy":"REPLACE"}', 'type': 'ItemTimeSeriesEvent'} in on_sse_event:
[2024-07-16 07:51:01,010] [                   HABApp]    ERROR | File "/opt/habapp/lib/python3.11/site-packages/HABApp/openhab/process_events.py", line 44 in on_sse_event
[2024-07-16 07:51:01,010] [                   HABApp]    ERROR | --------------------------------------------------------------------------------
[2024-07-16 07:51:01,010] [                   HABApp]    ERROR |      41 | def on_sse_event(event_dict: dict, oh_3: bool):
[2024-07-16 07:51:01,010] [                   HABApp]    ERROR |      42 |     try:
[2024-07-16 07:51:01,010] [                   HABApp]    ERROR |      43 |         # Lookup corresponding OpenHAB event
[2024-07-16 07:51:01,010] [                   HABApp]    ERROR | -->  44 |         event = get_event(event_dict)
[2024-07-16 07:51:01,010] [                   HABApp]    ERROR |      46 |         # Update item in registry BEFORE posting to the event bus
[2024-07-16 07:51:01,010] [                   HABApp]    ERROR |      47 |         # so the items have the correct state when we process the event in a rule
[2024-07-16 07:51:01,010] [                   HABApp]    ERROR |    ------------------------------------------------------------
[2024-07-16 07:51:01,010] [                   HABApp]    ERROR |      (ItemAddedEvent, ItemUpdatedEvent) = (<class 'HABApp.openhab.events.item_events.ItemAddedEvent'>, <class 'HABApp.openhab.events.item_events.ItemUpdatedEvent'>)
[2024-07-16 07:51:01,010] [                   HABApp]    ERROR |      (ThingStatusInfoEvent, ThingUpdatedEvent, ThingConfigStatusInfoEvent) = (<class 'HABApp.openhab.events.thing_events.ThingStatusInfoEvent'>, <class 'HABApp.openhab.events.thing_events.ThingUpdatedEvent'>, <class 'HABApp.openhab.events.thing_events.ThingConfigStatusInfoEvent'>)
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      e = ValueError('Unknown Event: ItemTimeSeriesEvent for {\'topic\': \'openhab/items/Tibber_CurrentTotal/timeseries\', \'payload\': \'{"timeSeries":[{"type":"Decimal","value":"0.2736","timestamp":"2024-07-15T22:00:00Z"},{"type":"Decimal","value":"0.2583","timestamp":"2024-07-15T23:00:00Z"},{"type":"Decimal","value":"0.2449","timestamp":"2024-07-16T00:00:00Z"},{"type":"Decimal","value":"0.2263","timestamp":"2024-07-16T01:00:00Z"},{"type":"Decimal","value":"0.2278","timestamp":"2024-07-16T02:00:00Z"},{"type":"Decimal","value":"0.2423","timestamp":"2024-07-16T03:00:00Z"},{"type":"Decimal","value":"0.2781","timestamp":"2024-07-16T04:00:00Z"},{"type":"Decimal","value":"0.2907","timestamp":"2024-07-16T05:00:00Z"},{"type":"Decimal","value":"0.2828","timestamp":"2024-07-16T06:00:00Z"},{"type":"Decimal","value":"0.2571","timestamp":"2024-07-16T07:00:00Z"},{"type":"Decimal","value":"0.208","timestamp":"2024-07-16T08:00:00Z"},{"type":"Decimal","value":"0.1825","timestamp":"2024-07-16T09:00:00Z"},{"type":"Decimal","value":"0.1729","timestamp":"2024-07-16T10:00:00Z"},{"type":"Decimal","value":"0.1693","timestamp":"2024-07-16T11:00:00Z"},{"type":"Decimal","value":"0.1688","timestamp":"2024-07-16T12:00:00Z"},{"type":"Decimal","value":"0.1692","timestamp":"2024-07-16T13:00:00Z"},{"type":"Decimal","value":"0.1797","timestamp":"2024-07-16T14:00:00Z"},{"type":"Decimal","value":"0.2088","timestamp":"2024-07-16T15:00:00Z"},{"type":"Decimal","value":"0.2574","timestamp":"2024-07-16T16:00:00Z"},{"type":"Decimal","value":"0.28","timestamp":"2024-07-16T17:00:00Z"},{"type":"Decimal","value":"0.3271","timestamp":"2024-07-16T18:00:00Z"},{"type":"Decimal","value":"0.3184","timestamp":"2024-07-16T19:00:00Z"},{"type":"Decimal","value":"0.3084","timestamp":"2024-07-16T20:00:00Z"},{"type":"Decimal","value":"0.2828","timestamp":"2024-07-16T21:00:00Z"}],"policy":"REPLACE"}\', \'type\': \'ItemTimeSeriesEvent\'}')
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      event_dict = {'topic': 'openhab/items/Tibber_CurrentTotal/timeseries', 'payload': '{"timeSeries":[{"type":"Decimal","value":"0.2736","timestamp":"2024-07-15T22:00:00Z"},{"type":"Decimal","value":"0.2583","timestamp":"2024-07-15T23:00:00Z"},{"type":"Decimal","value":"0.2449","timestamp":"2024-07-16T00:00:00Z"},{"type":"Decimal","value":"0.2263","timestamp":"2024-07-16T01:00:00Z"},{"type":"Decimal","value":"0.2278","timestamp":"2024-07-16T02:00:00Z"},{"type":"Decimal","value":"0.2423","timestamp":"2024-07-16T03:00:00Z"},{"type":"Decimal","value":"0.2781","timestamp":"2024-07-16T04:00:00Z"},{"type":"Decimal","value":"0.2907","timestamp":"2024-07-16T05:00:00Z"},{"type":"Decimal","value":"0.2828","timestamp":"2024-07-16T06:00:00Z"},{"type":"Decimal","value":"0.2571","timestamp":"2024-07-16T07:00:00Z"},{"type":"Decimal","value":"0.208","timestamp":"2024-07-16T08:00:00Z"},{"type":"Decimal","value":"0.1825","timestamp":"2024-07-16T09:00:00Z"},{"type":"Decimal","value":"0.1729","timestamp":"2024-07-16T10:00:00Z"},{"type":"Decimal","value":"0.1693","timestamp":"2024-07-16T11:00:00Z"},{"type":"Decimal","value":"0.1688","timestamp":"2024-07-16T12:00:00Z"},{"type":"Decimal","value":"0.1692","timestamp":"2024-07-16T13:00:00Z"},{"type":"Decimal","value":"0.1797","timestamp":"2024-07-16T14:00:00Z"},{"type":"Decimal","value":"0.2088","timestamp":"2024-07-16T15:00:00Z"},{"type":"Decimal","value":"0.2574","timestamp":"2024-07-16T16:00:00Z"},{"type":"Decimal","value":"0.28","timestamp":"2024-07-16T17:00:00Z"},{"type":"Decimal","value":"0.3271","timestamp":"2024-07-16T18:00:00Z"},{"type":"Decimal","value":"0.3184","timestamp":"2024-07-16T19:00:00Z"},{"type":"Decimal","value":"0.3084","timestamp":"2024-07-16T20:00:00Z"},{"type":"Decimal","value":"0.2828","timestamp":"2024-07-16T21:00:00Z"}],"policy":"REPLACE"}', 'type': 'ItemTimeSeriesEvent'}
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      log = <Logger HABApp.openhab.items (INFO)>
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      oh_3 = False
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      oh_3 and isinstance(event, GroupStateChangedEvent) = False
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      TOPIC_ITEMS = 'openHAB.Items'
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      TOPIC_THINGS = 'openHAB.Things'
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |    ------------------------------------------------------------
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR | 
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR | File "/opt/habapp/lib/python3.11/site-packages/HABApp/openhab/map_events.py", line 47 in get_event
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR | --------------------------------------------------------------------------------
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      37 | def get_event(_in_dict: dict) -> OpenhabEvent:
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |       (...)
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      44 |         return _events[event_type].from_dict(topic, payload)
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      45 |     except KeyError:
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      46 |         msg = f'Unknown Event: {event_type:s} for {_in_dict}'
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR | -->  47 |         raise ValueError(msg) from None
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |    ------------------------------------------------------------
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      _events = {'ItemStateEvent': <class 'HABApp.openhab.events.item_events.ItemStateEvent'>, 'ItemStateUpdatedEvent': <class 'HABApp.openhab.events.item_events.ItemStateUpdatedEvent'>, 'ItemStateChangedEvent': <class 'HABApp.openhab.events.item_events.ItemStateChangedEvent'>, 'ItemCommandEvent': <class 'HABApp.openhab.events.item_events.ItemCommandEvent'>, 'ItemAddedEvent': <class 'HABApp.openhab.events.item_events.ItemAddedEvent'>, 'ItemUpdatedEvent': <class 'HABApp.openhab.events.item_events.ItemUpdatedEvent'>, 'ItemRemovedEvent': <class 'HABApp.openhab.events.item_events.ItemRemovedEvent'>, 'ItemStatePredictedEvent': <class 'HABApp.openhab.events.item_events.ItemStatePredictedEvent'>, 'GroupStateUpdatedEvent': <class 'HABApp.openhab.events.item_events.GroupStateUpdatedEvent'>, 'GroupStateChangedEvent': <class 'HABApp.openhab.events.item_events.GroupStateChangedEvent'>, 'ChannelTriggeredEvent': <class 'HABApp.openhab.events.channel_events.ChannelTriggeredEvent'>, 'ChannelDescriptionChangedEvent': <class 'HABApp.openhab.events.channel_events.ChannelDescriptionChangedEvent'>, 'ThingAddedEvent': <class 'HABApp.openhab.events.thing_events.ThingAddedEvent'>, 'ThingRemovedEvent': <class 'HABApp.openhab.events.thing_events.ThingRemovedEvent'>, 'ThingUpdatedEvent': <class 'HABApp.openhab.events.thing_events.ThingUpdatedEvent'>, 'ThingStatusInfoEvent': <class 'HABApp.openhab.events.thing_events.ThingStatusInfoEvent'>, 'ThingStatusInfoChangedEvent': <class 'HABApp.openhab.events.thing_events.ThingStatusInfoChangedEvent'>, 'ThingFirmwareStatusInfoEvent': <class 'HABApp.openhab.events.thing_events.ThingFirmwareStatusInfoEvent'>, 'ThingConfigStatusInfoEvent': <class 'HABApp.openhab.events.thing_events.ThingConfigStatusInfoEvent'>, 'GroupItemStateChangedEvent': <class 'HABApp.openhab.events.item_events.GroupStateChangedEvent'>, 'FirmwareStatusInfoEvent': <class 'HABApp.openhab.events.thing_events.ThingFirmwareStatusInfoEvent'>, 'ConfigStatusInfoEvent': <class 'HABApp.openhab.events.thing_events.ThingConfigStatusInfoEvent'>}
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      _in_dict = {'topic': 'openhab/items/Tibber_CurrentTotal/timeseries', 'payload': '{"timeSeries":[{"type":"Decimal","value":"0.2736","timestamp":"2024-07-15T22:00:00Z"},{"type":"Decimal","value":"0.2583","timestamp":"2024-07-15T23:00:00Z"},{"type":"Decimal","value":"0.2449","timestamp":"2024-07-16T00:00:00Z"},{"type":"Decimal","value":"0.2263","timestamp":"2024-07-16T01:00:00Z"},{"type":"Decimal","value":"0.2278","timestamp":"2024-07-16T02:00:00Z"},{"type":"Decimal","value":"0.2423","timestamp":"2024-07-16T03:00:00Z"},{"type":"Decimal","value":"0.2781","timestamp":"2024-07-16T04:00:00Z"},{"type":"Decimal","value":"0.2907","timestamp":"2024-07-16T05:00:00Z"},{"type":"Decimal","value":"0.2828","timestamp":"2024-07-16T06:00:00Z"},{"type":"Decimal","value":"0.2571","timestamp":"2024-07-16T07:00:00Z"},{"type":"Decimal","value":"0.208","timestamp":"2024-07-16T08:00:00Z"},{"type":"Decimal","value":"0.1825","timestamp":"2024-07-16T09:00:00Z"},{"type":"Decimal","value":"0.1729","timestamp":"2024-07-16T10:00:00Z"},{"type":"Decimal","value":"0.1693","timestamp":"2024-07-16T11:00:00Z"},{"type":"Decimal","value":"0.1688","timestamp":"2024-07-16T12:00:00Z"},{"type":"Decimal","value":"0.1692","timestamp":"2024-07-16T13:00:00Z"},{"type":"Decimal","value":"0.1797","timestamp":"2024-07-16T14:00:00Z"},{"type":"Decimal","value":"0.2088","timestamp":"2024-07-16T15:00:00Z"},{"type":"Decimal","value":"0.2574","timestamp":"2024-07-16T16:00:00Z"},{"type":"Decimal","value":"0.28","timestamp":"2024-07-16T17:00:00Z"},{"type":"Decimal","value":"0.3271","timestamp":"2024-07-16T18:00:00Z"},{"type":"Decimal","value":"0.3184","timestamp":"2024-07-16T19:00:00Z"},{"type":"Decimal","value":"0.3084","timestamp":"2024-07-16T20:00:00Z"},{"type":"Decimal","value":"0.2828","timestamp":"2024-07-16T21:00:00Z"}],"policy":"REPLACE"}', 'type': 'ItemTimeSeriesEvent'}
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      _in_dict['payload'] = '{"timeSeries":[{"type":"Decimal","value":"0.2736","timestamp":"2024-07-15T22:00:00Z"},{"type":"Decimal","value":"0.2583","timestamp":"2024-07-15T23:00:00Z"},{"type":"Decimal","value":"0.2449","timestamp":"2024-07-16T00:00:00Z"},{"type":"Decimal","value":"0.2263","timestamp":"2024-07-16T01:00:00Z"},{"type":"Decimal","value":"0.2278","timestamp":"2024-07-16T02:00:00Z"},{"type":"Decimal","value":"0.2423","timestamp":"2024-07-16T03:00:00Z"},{"type":"Decimal","value":"0.2781","timestamp":"2024-07-16T04:00:00Z"},{"type":"Decimal","value":"0.2907","timestamp":"2024-07-16T05:00:00Z"},{"type":"Decimal","value":"0.2828","timestamp":"2024-07-16T06:00:00Z"},{"type":"Decimal","value":"0.2571","timestamp":"2024-07-16T07:00:00Z"},{"type":"Decimal","value":"0.208","timestamp":"2024-07-16T08:00:00Z"},{"type":"Decimal","value":"0.1825","timestamp":"2024-07-16T09:00:00Z"},{"type":"Decimal","value":"0.1729","timestamp":"2024-07-16T10:00:00Z"},{"type":"Decimal","value":"0.1693","timestamp":"2024-07-16T11:00:00Z"},{"type":"Decimal","value":"0.1688","timestamp":"2024-07-16T12:00:00Z"},{"type":"Decimal","value":"0.1692","timestamp":"2024-07-16T13:00:00Z"},{"type":"Decimal","value":"0.1797","timestamp":"2024-07-16T14:00:00Z"},{"type":"Decimal","value":"0.2088","timestamp":"2024-07-16T15:00:00Z"},{"type":"Decimal","value":"0.2574","timestamp":"2024-07-16T16:00:00Z"},{"type":"Decimal","value":"0.28","timestamp":"2024-07-16T17:00:00Z"},{"type":"Decimal","value":"0.3271","timestamp":"2024-07-16T18:00:00Z"},{"type":"Decimal","value":"0.3184","timestamp":"2024-07-16T19:00:00Z"},{"type":"Decimal","value":"0.3084","timestamp":"2024-07-16T20:00:00Z"},{"type":"Decimal","value":"0.2828","timestamp":"2024-07-16T21:00:00Z"}],"policy":"REPLACE"}'
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      _in_dict['topic'] = 'openhab/items/Tibber_CurrentTotal/timeseries'
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      _in_dict['type'] = 'ItemTimeSeriesEvent'
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      event_type = 'ItemTimeSeriesEvent'
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      msg = 'Unknown Event: ItemTimeSeriesEvent for {\'topic\': \'openhab/items/Tibber_CurrentTotal/timeseries\', \'payload\': \'{"timeSeries":[{"type":"Decimal","value":"0.2736","timestamp":"2024-07-15T22:00:00Z"},{"type":"Decimal","value":"0.2583","timestamp":"2024-07-15T23:00:00Z"},{"type":"Decimal","value":"0.2449","timestamp":"2024-07-16T00:00:00Z"},{"type":"Decimal","value":"0.2263","timestamp":"2024-07-16T01:00:00Z"},{"type":"Decimal","value":"0.2278","timestamp":"2024-07-16T02:00:00Z"},{"type":"Decimal","value":"0.2423","timestamp":"2024-07-16T03:00:00Z"},{"type":"Decimal","value":"0.2781","timestamp":"2024-07-16T04:00:00Z"},{"type":"Decimal","value":"0.2907","timestamp":"2024-07-16T05:00:00Z"},{"type":"Decimal","value":"0.2828","timestamp":"2024-07-16T06:00:00Z"},{"type":"Decimal","value":"0.2571","timestamp":"2024-07-16T07:00:00Z"},{"type":"Decimal","value":"0.208","timestamp":"2024-07-16T08:00:00Z"},{"type":"Decimal","value":"0.1825","timestamp":"2024-07-16T09:00:00Z"},{"type":"Decimal","value":"0.1729","timestamp":"2024-07-16T10:00:00Z"},{"type":"Decimal","value":"0.1693","timestamp":"2024-07-16T11:00:00Z"},{"type":"Decimal","value":"0.1688","timestamp":"2024-07-16T12:00:00Z"},{"type":"Decimal","value":"0.1692","timestamp":"2024-07-16T13:00:00Z"},{"type":"Decimal","value":"0.1797","timestamp":"2024-07-16T14:00:00Z"},{"type":"Decimal","value":"0.2088","timestamp":"2024-07-16T15:00:00Z"},{"type":"Decimal","value":"0.2574","timestamp":"2024-07-16T16:00:00Z"},{"type":"Decimal","value":"0.28","timestamp":"2024-07-16T17:00:00Z"},{"type":"Decimal","value":"0.3271","timestamp":"2024-07-16T18:00:00Z"},{"type":"Decimal","value":"0.3184","timestamp":"2024-07-16T19:00:00Z"},{"type":"Decimal","value":"0.3084","timestamp":"2024-07-16T20:00:00Z"},{"type":"Decimal","value":"0.2828","timestamp":"2024-07-16T21:00:00Z"}],"policy":"REPLACE"}\', \'type\': \'ItemTimeSeriesEvent\'}'
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      payload = {'timeSeries': [{'type': 'Decimal', 'value': '0.2736', 'timestamp': '2024-07-15T22:00:00Z'}, {'type': 'Decimal', 'value': '0.2583', 'timestamp': '2024-07-15T23:00:00Z'}, {'type': 'Decimal', 'value': '0.2449', 'timestamp': '2024-07-16T00:00:00Z'}, {'type': 'Decimal', 'value': '0.2263', 'timestamp': '2024-07-16T01:00:00Z'}, {'type': 'Decimal', 'value': '0.2278', 'timestamp': '2024-07-16T02:00:00Z'}, {'type': 'Decimal', 'value': '0.2423', 'timestamp': '2024-07-16T03:00:00Z'}, {'type': 'Decimal', 'value': '0.2781', 'timestamp': '2024-07-16T04:00:00Z'}, {'type': 'Decimal', 'value': '0.2907', 'timestamp': '2024-07-16T05:00:00Z'}, {'type': 'Decimal', 'value': '0.2828', 'timestamp': '2024-07-16T06:00:00Z'}, {'type': 'Decimal', 'value': '0.2571', 'timestamp': '2024-07-16T07:00:00Z'}, {'type': 'Decimal', 'value': '0.208', 'timestamp': '2024-07-16T08:00:00Z'}, {'type': 'Decimal', 'value': '0.1825', 'timestamp': '2024-07-16T09:00:00Z'}, {'type': 'Decimal', 'value': '0.1729', 'timestamp': '2024-07-16T10:00:00Z'}, {'type': 'Decimal', 'value': '0.1693', 'timestamp': '2024-07-16T11:00:00Z'}, {'type': 'Decimal', 'value': '0.1688', 'timestamp': '2024-07-16T12:00:00Z'}, {'type': 'Decimal', 'value': '0.1692', 'timestamp': '2024-07-16T13:00:00Z'}, {'type': 'Decimal', 'value': '0.1797', 'timestamp': '2024-07-16T14:00:00Z'}, {'type': 'Decimal', 'value': '0.2088', 'timestamp': '2024-07-16T15:00:00Z'}, {'type': 'Decimal', 'value': '0.2574', 'timestamp': '2024-07-16T16:00:00Z'}, {'type': 'Decimal', 'value': '0.28', 'timestamp': '2024-07-16T17:00:00Z'}, {'type': 'Decimal', 'value': '0.3271', 'timestamp': '2024-07-16T18:00:00Z'}, {'type': 'Decimal', 'value': '0.3184', 'timestamp': '2024-07-16T19:00:00Z'}, {'type': 'Decimal', 'value': '0.3084', 'timestamp': '2024-07-16T20:00:00Z'}, {'type': 'Decimal', 'value': '0.2828', 'timestamp': '2024-07-16T21:00:00Z'}], 'policy': 'REPLACE'}
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |      topic = 'openhab/items/Tibber_CurrentTotal/timeseries'
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |    ------------------------------------------------------------
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR | 
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR | --------------------------------------------------------------------------------
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR | Traceback (most recent call last):
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |   File "/opt/habapp/lib/python3.11/site-packages/HABApp/openhab/process_events.py", line 44, in on_sse_event
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |     event = get_event(event_dict)
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |             ^^^^^^^^^^^^^^^^^^^^^
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |   File "/opt/habapp/lib/python3.11/site-packages/HABApp/openhab/map_events.py", line 47, in get_event
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR |     raise ValueError(msg) from None
[2024-07-16 07:51:01,011] [                   HABApp]    ERROR | ValueError: Unknown Event: ItemTimeSeriesEvent for {'topic': 'openhab/items/Tibber_CurrentTotal/timeseries', 'payload': '{"timeSeries":[{"type":"Decimal","value":"0.2736","timestamp":"2024-07-15T22:00:00Z"},{"type":"Decimal","value":"0.2583","timestamp":"2024-07-15T23:00:00Z"},{"type":"Decimal","value":"0.2449","timestamp":"2024-07-16T00:00:00Z"},{"type":"Decimal","value":"0.2263","timestamp":"2024-07-16T01:00:00Z"},{"type":"Decimal","value":"0.2278","timestamp":"2024-07-16T02:00:00Z"},{"type":"Decimal","value":"0.2423","timestamp":"2024-07-16T03:00:00Z"},{"type":"Decimal","value":"0.2781","timestamp":"2024-07-16T04:00:00Z"},{"type":"Decimal","value":"0.2907","timestamp":"2024-07-16T05:00:00Z"},{"type":"Decimal","value":"0.2828","timestamp":"2024-07-16T06:00:00Z"},{"type":"Decimal","value":"0.2571","timestamp":"2024-07-16T07:00:00Z"},{"type":"Decimal","value":"0.208","timestamp":"2024-07-16T08:00:00Z"},{"type":"Decimal","value":"0.1825","timestamp":"2024-07-16T09:00:00Z"},{"type":"Decimal","value":"0.1729","timestamp":"2024-07-16T10:00:00Z"},{"type":"Decimal","value":"0.1693","timestamp":"2024-07-16T11:00:00Z"},{"type":"Decimal","value":"0.1688","timestamp":"2024-07-16T12:00:00Z"},{"type":"Decimal","value":"0.1692","timestamp":"2024-07-16T13:00:00Z"},{"type":"Decimal","value":"0.1797","timestamp":"2024-07-16T14:00:00Z"},{"type":"Decimal","value":"0.2088","timestamp":"2024-07-16T15:00:00Z"},{"type":"Decimal","value":"0.2574","timestamp":"2024-07-16T16:00:00Z"},{"type":"Decimal","value":"0.28","timestamp":"2024-07-16T17:00:00Z"},{"type":"Decimal","value":"0.3271","timestamp":"2024-07-16T18:00:00Z"},{"type":"Decimal","value":"0.3184","timestamp":"2024-07-16T19:00:00Z"},{"type":"Decimal","value":"0.3084","timestamp":"2024-07-16T20:00:00Z"},{"type":"Decimal","value":"0.2828","timestamp":"2024-07-16T21:00:00Z"}],"policy":"REPLACE"}', 'type': 'ItemTimeSeriesEvent'}

**Comment by spacemanspiff2007** [comment]
Can you try the [DEV](https://habapp.readthedocs.io/en/latest/installation.html#install-a-development-version-of-habapp) branch and see if this fixes your issues?

**Comment by silentsimmal** [comment]
The issue seems to be fixed on the DEV branch.

**Comment by spacemanspiff2007** [comment]
Fixed in 24.08.0
