### ISSUE TITLE
Clean approach to rule libraries

### ISSUE THREAD

**Issue by SPF79** [spacemanspiff2007/HABApp#455]
Heya,

I've been using HABApp very intensively for a few years now and completely replaced all other OpenHAB rule configurations. First of all, many thanks for all the good work.

But second of all, I'm a little puzzled in regards to how to organise my ever growing rule library and utilise it correctly.

To give a brief hint of what my issue here is: I'm using Milight devices extensively in my home automation. I'm hitch-hiking their native lightweight protocol with MilightHubs (node MCU's) to provide wireless interfaces for almost everything in conjunction with RaspberryMatic and other Pi's for custom e.g. relay operations as well as MQTT as the obvious standard middle-ware.

The problem I'm facing, is I now developed a highly-sophisticated low-level python library for Milight based on your HABApp rule system and would really like to employ it as a common dependency for further rule development, but I have no idea how to approach it. You know, having a milight rule module, that I can e.g. import when writing new rules (and as the cream on top, having JetBrains' IntelliJ showing me proper inspection results, so I can ditch more trial & error).

I'm not sure whether this is the right scenery for this request, but I would really like you to give me a hint/setup that is most viable to employ with in-depth Python programming when using your framework.

All the best,

Seb

**Comment by spacemanspiff2007** [comment]
As always it depends.
If your work is relatively stable you can create a module in the lib folder (see docs) and import that module in your rule files.
This will also provide IDE hints as expected. However changes in the module will not be picked up during runtime so you have to restart HABApp every time you change something in the module.
The second way is to use ``self.get_rule`` to access a rule you might have created for a device. See docs how to make that work with type hints. The upside is that this way you can dynamically reload your library without having to restart HABApp. It's a little bit more verbose when making the calls so whether it's feasible depends on your implementation.
The third way is to just use HABApp internal items. Since they can hold any data structure it's possible to e.g. pass dataclasses around. The pro is that you'll have a nice interface and proper decoupling, however if you want to work with e.g. return values of functions calls it's not very nice. This works also with type hints (same as the second option).
For option 2 and 3 it's also possible to define the source files as a dependency and I recommend doing so that the files will be loaded in correct order.

I mostly use the HABApp internal items and for pushover notifications I use the get rules.
The internal items make nice processing pipelines, because I can trigger on changes and on updates.
E.g. I have a rule which loads the weather forecast and posts the whole forecast into one item.
Then I have another rule in another file which on an update of that item does some logic depending on the forecast.

Without knowing the details I can't recommend you which way to go but these are your options.
However I recommend you play a little bit with option 3 or 2 and only if that's not a good fit I'd try out option 1.

**Comment by SPF79** [comment]
Hi again,

cheers, mate. That should be it for now and I'll do my research on options
2 and 3. Maybe I find something that works well for my setup.

If you should ever need anything (and be it a beta tester), give me a
holler. I'm a man of duty and honour and you, my friend, deserve both when
it comes to me.

All the best and hang in there,

Seb

Am Fr., 27. Sept. 2024 um 14:52 Uhr schrieb spacemanspiff2007 <
***@***.***>:

**Comment by SPF79** [comment]
Hi again,

I have another (minor) problem, that's haunting me and I thought I clear it
up right now, as I triggered you already and then leave you to it:

I developed a party gimmick, fetching the album art of the currently
playing Spotify song, save it to disc, load it with pillow and grap the
most dominant colours therein with colorthief to provide HSB/RGB values for
MIlight mood lighting whenever the song changes. It looks great and is fun,
but I'm facing bytes assertion errors (that I didn't really handle  yet,
because I was reverting a lot on GIT to keep my important stuff running -
so disabled for now).

Now for the tiny issue: When this assertion issue happens HABApp slams the
frickin' whole image at that time into the log! Which means my /var/log
partition is full in the matter of a day. My question is: How can I stop
this (omit the content of this specific the item for the log) and have some
peace when tinkering instead of everything shutting down because of "No
space left on device"?

Best,

Seb

Am Fr., 27. Sept. 2024 um 14:52 Uhr schrieb spacemanspiff2007 <
***@***.***>:

**Comment by spacemanspiff2007** [comment]
Sounds like a nice feature.
You could write a custom logging filter which prevents lines where this name occurs to be printed.
The filter can be loaded during startup via the ``HABAppUser`` module.
However the more simple solution would be to just remove the assertion or handle it gracefully.
Do the check and if it fails emit a small log message and return from the function.
Or wrap the whole function, catch the AssertionError and log only the error.

**Comment by SPF79** [comment]
After some more research, it's not my code throwing the AssertionError. It's your's.

Apparently when a new Base64 image is set to the item, your item_reg (?) code can't handle that and throws me a bunch. Here is an excerpt:

[HABApp.txt](https://github.com/user-attachments/files/17265771/HABApp.txt)

Any ideas?

**Comment by spacemanspiff2007** [comment]
There seems to be the interesting parts of the traceback missing where it throws the assertion error. 
Would it be possible to attach the whole traceback? You can also pm it to me in the openHAB forums if you want to.

**Comment by SPF79** [comment]
I had to do it over here because of the 1MB openhab upload limit (didn't get around to implement a logging filter yet) and also deleted the last to inline images.

[HABApp.log](https://github.com/user-attachments/files/17267104/HABApp.log)

**Comment by spacemanspiff2007** [comment]
I see two issues: 
1. The ```ValueError: Chunk too big```. See troubleshooting in docs how to fix it.
2. The assertion error during startup. That's a bug, I'll investigate further.
```
2024-10-05 20:12:52.613 [ERROR] [HABApp                              ] - File "/opt/habapp/lib/python3.9/site-packages/HABApp/openhab/items/image_item.py", line 67 in set_value
2024-10-05 20:12:52.613 [ERROR] [HABApp                              ] - --------------------------------------------------------------------------------
2024-10-05 20:12:52.613 [ERROR] [HABApp                              ] -      66 | def set_value(self, new_value) -> bool:
2024-10-05 20:12:52.613 [ERROR] [HABApp                              ] - -->  67 |     assert isinstance(new_value, RawValue) or new_value is None, type(new_value)
2024-10-05 20:12:52.613 [ERROR] [HABApp                              ] -      69 |     if new_value is None:
2024-10-05 20:12:52.613 [ERROR] [HABApp                              ] -    ------------------------------------------------------------
2024-10-05 20:12:52.614 [ERROR] [HABApp                              ] -      self = <ImageItem name: spotifyAlbumImage, value: b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00`\x00`\x00\x00\xff\xfe\x00;CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), quality = 90\n\xff\xd...'
2024-10-05 20:12:52.620 [ERROR] [HABApp                              ] -    ------------------------------------------------------------
2024-10-05 20:12:52.620 [ERROR] [HABApp                              ] - 
2024-10-05 20:12:52.620 [ERROR] [HABApp                              ] - --------------------------------------------------------------------------------
2024-10-05 20:12:52.620 [ERROR] [HABApp                              ] - Traceback (most recent call last):
2024-10-05 20:12:52.621 [ERROR] [HABApp                              ] -   File "/opt/habapp/lib/python3.9/site-packages/HABApp/core/connections/base_connection.py", line 173, in _task_plugin
2024-10-05 20:12:52.621 [ERROR] [HABApp                              ] -     await cb.run(self, self.context)
2024-10-05 20:12:52.621 [ERROR] [HABApp                              ] -   File "/opt/habapp/lib/python3.9/site-packages/HABApp/core/connections/plugin_callback.py", line 53, in run
2024-10-05 20:12:52.621 [ERROR] [HABApp                              ] -     return await self.coro(**kwargs)
2024-10-05 20:12:52.621 [ERROR] [HABApp                              ] -   File "/opt/habapp/lib/python3.9/site-packages/HABApp/openhab/connection/plugins/load_items.py", line 41, in on_connected
2024-10-05 20:12:52.621 [ERROR] [HABApp                              ] -     await self.load_items(context)
2024-10-05 20:12:52.621 [ERROR] [HABApp                              ] -   File "/opt/habapp/lib/python3.9/site-packages/HABApp/openhab/connection/plugins/load_items.py", line 91, in load_items
2024-10-05 20:12:52.621 [ERROR] [HABApp                              ] -     add_to_registry(new_item, True)
2024-10-05 20:12:52.621 [ERROR] [HABApp                              ] -   File "/opt/habapp/lib/python3.9/site-packages/HABApp/openhab/item_to_reg.py", line 41, in add_to_registry
2024-10-05 20:12:52.621 [ERROR] [HABApp                              ] -     existing.set_value(item.value)
2024-10-05 20:12:52.622 [ERROR] [HABApp                              ] -   File "/opt/habapp/lib/python3.9/site-packages/HABApp/openhab/items/image_item.py", line 67, in set_value
2024-10-05 20:12:52.622 [ERROR] [HABApp                              ] -     assert isinstance(new_value, RawValue) or new_value is None, type(new_value)
2024-10-05 20:12:52.622 [ERROR] [HABApp                              ] - AssertionError: <class 'bytes'>
```

**Comment by spacemanspiff2007** [comment]
I assume you have no persistence strategy set up for the image item. If you restart openHAB or set it to NULL through the API explorer HABApp will start and work as expected.

**Comment by SPF79** [comment]
Great, thank you for the heads-up. Done and tested with the same song, that produced the error before. No issues.

I now remember fixing this once already (buffer size), before my abominable divorce and reckon these to be the forensic trace back:

1. Working setup
2. Time and horror passed...
3. Update of OpenHAB + HABApp (changes to config.yml fields therein)
4. Moved mosquitto to a different machine (tons of work + trial & error)
5. Reconfigured HABApp with a clean slate config.yml, because of some LF/CR anomaly (superficially, since the working 'buffer' setting vanished) **Critique: YML sucks arse and this has nothing to do with ansible. What's wrong with JSON? YML strikes me as sorta hipster-wookie. ;-)**
6. The AssertionError and tons of inline images in the log overshadowing the 'chuck too big' issue.

Thank you very much for all the support and all the best with the AssertionError.

Best,

Seb

**Comment by SPF79** [comment]
Solved.

**Comment by spacemanspiff2007** [comment]
Do you still get the error after setting your buffer accordingly?

**Comment by SPF79** [comment]
> Done and tested with the same song, that produced the error before. No issues.

Nope. ^_^

**Comment by spacemanspiff2007** [comment]
Ah - I thought that was the answer for the workaround suggestion.
But now it's clear.
