### ISSUE TITLE
HABApp on Kubernetes - The Next Issue: Startup Errors

### ISSUE THREAD

**Issue by RichieRogers** [spacemanspiff2007/HABApp#458]
Hi,
Having finally getting HABApp to deploy into Kubernetes, I'm now hitting an issue with these errors, which are obviously then preventing connection to my OpenHAB instance.

````
[2024-10-21 12:34:57,180] [                   HABApp]     INFO | HABApp Version 24.08.1
[2024-10-21 12:34:57,180] [            HABApp.Config]  WARNING | Replaced class for handler "HABApp_default" with HABApp.config.logging.MidnightRotatingFileHandler
[2024-10-21 12:34:57,180] [            HABApp.Config]  WARNING | Replaced class for handler "EventFile" with HABApp.config.logging.MidnightRotatingFileHandler
[2024-10-21 12:34:57,180] [            HABApp.Config]  WARNING | Replaced class for handler "OHRuleHandler" with HABApp.config.logging.MidnightRotatingFileHandler
[2024-10-21 12:34:57,180] [            HABApp.Config]  WARNING | Replaced class for handler "OHRVLoungeStatusHandler" with HABApp.config.logging.MidnightRotatingFileHandler
[2024-10-21 12:34:57,180] [            HABApp.Config]  WARNING | Replaced class for handler "OHRVBackBedStatusHandler" with HABApp.config.logging.MidnightRotatingFileHandler
[2024-10-21 12:34:57,180] [            HABApp.Config]  WARNING | Replaced class for handler "OHRSSHandler" with HABApp.config.logging.MidnightRotatingFileHandler
[2024-10-21 12:34:57,241] [                   HABApp]    ERROR | Error  in on_setup:
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR | Error while formatting traceback: type object 'bool' has no attribute 'key'
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR | Traceback (most recent call last):
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.11/site-packages/HABApp/core/connections/base_connection.py", line 173, in _task_plugin
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |     await cb.run(self, self.context)
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.11/site-packages/HABApp/core/connections/plugin_callback.py", line 53, in run
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |     return await self.coro(**kwargs)
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |            ^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.11/site-packages/HABApp/openhab/connection/plugins/plugin_things/plugin_things.py", line 63, in on_setup
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |     self.watcher = folder.add_watch('.yml')
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |                    ^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.11/site-packages/HABApp/core/files/folders/folders.py", line 32, in add_watch
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |     HABApp.core.files.watcher.add_folder_watch(handler)
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.11/site-packages/HABApp/core/files/watcher/folder_watcher.py", line 47, in add_folder_watch
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |     assert _folder not in WATCHES
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |            ^^^^^^^^^^^^^^^^^^^^^^
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR | AssertionError
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR | During handling of the above exception, another exception occurred:
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR | Traceback (most recent call last):
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.11/site-packages/HABApp/core/lib/exceptions/format.py", line 59, in format_exception
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |     added = format_frame_info(tb, frame_info, is_last=i == last_frame)
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.11/site-packages/HABApp/core/lib/exceptions/format_frame.py", line 79, in format_frame_info
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |     format_frame_variables(tb, frame_info.variables)
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.11/site-packages/HABApp/core/lib/exceptions/format_frame_vars.py", line 86, in format_frame_variables
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |     used_vars: List[Variable] = [v for v in stack_variables if not skip_variable(v)]
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.11/site-packages/HABApp/core/lib/exceptions/format_frame_vars.py", line 86, in <listcomp>
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |     used_vars: List[Variable] = [v for v in stack_variables if not skip_variable(v)]
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |                                                                    ^^^^^^^^^^^^^^^^
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.11/site-packages/HABApp/core/lib/exceptions/format_frame_vars.py", line 76, in skip_variable
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |     if func(name, value):
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |        ^^^^^^^^^^^^^^^^^
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.11/site-packages/HABApp/core/lib/exceptions/format_frame_vars.py", line 55, in <lambda>
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |     lambda name, value: is_type_hint_or_type(value),
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.11/site-packages/HABApp/core/lib/exceptions/format_frame_vars.py", line 28, in is_type_hint_or_type
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |     if value in SKIPPED_TYPES:
[2024-10-21 12:34:57,242] [                   HABApp]    ERROR |        ^^^^^^^^^^^^^^^^^^^^^^
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |   File "/usr/local/lib/python3.11/site-packages/watchdog/observers/api.py", line 78, in __eq__
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |     return self.key == watch.key
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |                        ^^^^^^^^^
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR | AttributeError: type object 'bool' has no attribute 'key'
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR | --------------------------------------------------------------------------------
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR | Partial Traceback:
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR | --------------------------------------------------------------------------------
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR | File "/usr/local/lib/python3.11/site-packages/HABApp/openhab/connection/plugins/plugin_things/plugin_things.py", line 63 in on_setup
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR | --------------------------------------------------------------------------------
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      48 | async def on_setup(self):
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |       (...)
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      59 |         UNLOAD_FUNC = self.file_unload
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      61 |     folder = add_habapp_folder('config/', path, 50)
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      62 |     folder.add_file_type(HABAppThingConfigFile)
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR | -->  63 |     self.watcher = folder.add_watch('.yml')
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |    ------------------------------------------------------------
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      HABApp.CONFIG.directories.config = PosixPath('/habapp/config')
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      self = <HABApp.openhab.connection.plugins.plugin_things.plugin_things.TextualThingConfigPlugin object at 0x7fc0ed2e8d90>
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      self.watcher = None
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      add_habapp_folder = <function add_folder at 0x7fc0ed0a5300>
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      folder = <HABApp.core.files.folders.folders.ConfiguredFolder object at 0x7fc0ecd8d350>
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      log = <Logger HABApp.openhab.thing (INFO)>
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      path = PosixPath('/habapp/config')
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      self.watcher is not None = False
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |    ------------------------------------------------------------
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR | File "/usr/local/lib/python3.11/site-packages/HABApp/core/files/folders/folders.py", line 32 in add_watch
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR | --------------------------------------------------------------------------------
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      29 | def add_watch(self, file_ending: str, watch_subfolders: bool = True) -> AggregatingAsyncEventHandler:
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      30 |     filter = HABApp.core.files.watcher.FileEndingFilter(file_ending)
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      31 |     handler = AggregatingAsyncEventHandler(self.folder, _generate_file_events, filter, watch_subfolders)
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR | -->  32 |     HABApp.core.files.watcher.add_folder_watch(handler)
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |      33 |     return handler
[2024-10-21 12:34:57,243] [                   HABApp]    ERROR |    ------------------------------------------------------------
[2024-10-21 12:34:57,244] [                   HABApp]    ERROR |      watch_subfolders = True
[2024-10-21 12:34:57,244] [                   HABApp]    ERROR |    ------------------------------------------------------------
[2024-10-21 12:34:57,244] [                   HABApp]    ERROR |
[2024-10-21 12:34:57,244] [                   HABApp]    ERROR | File "/usr/local/lib/python3.11/site-packages/HABApp/core/files/watcher/folder_watcher.py", line 47 in add_folder_watch
[2024-10-21 12:34:57,244] [                   HABApp]    ERROR | --------------------------------------------------------------------------------
[2024-10-21 12:34:57,244] [                   HABApp]    ERROR |      36 | def add_folder_watch(handler: FileSystemEventHandler):
[2024-10-21 12:34:57,244] [                   HABApp]    ERROR |       (...)
[2024-10-21 12:34:57,244] [                   HABApp]    ERROR |      41 |     log.debug(
[2024-10-21 12:34:57,244] [                   HABApp]    ERROR |      42 |         f'Adding {"recursive " if handler.watch_subfolders else ""}watcher for {handler.folder} with {handler.filter}'
[2024-10-21 12:34:57,244] [                   HABApp]    ERROR |      43 |     )
[2024-10-21 12:34:57,244] [                   HABApp]    ERROR |      45 |     with LOCK:
[2024-10-21 12:34:57,244] [                   HABApp]    ERROR |      46 |         _folder = str(handler.folder)
[2024-10-21 12:34:57,244] [                   HABApp]    ERROR | -->  47 |         assert _folder not in WATCHES
[2024-10-21 12:34:57,244] [                   HABApp]    ERROR |      49 |         WATCHES[_folder] = OBSERVER.schedule(handler, _folder, recursive=handler.watch_subfolders)
````

My config.yml:

````yaml
    directories:
      logging: /habapp/log    # Folder where the logs will be written to
      rules: /habapp/rules    # Folder from which the rule files will be loaded
      param: /habapp/params   # Folder from which the parameter files will be loaded
      config: /habapp/config  # Folder from which configuration files (e.g. for textual thing configuration) will be loaded
      lib: /habapp/lib        # Folder where additional libraries can be placed
    location:
      latitude: REDACTED
      longitude: REDACTED
      elevation: 0.0
    mqtt:
      connection:
        identifier: HABAppPod   # Identifier that is used to uniquely identify this client on the mqtt broker.
        host: ''                           # Connect to this host. Empty string ("") disables the connection.
        port: 1883
        user: ''
        password: ''
        tls:
          enabled: false    # Enable TLS for the connection
          ca cert: .       # Path to a CA certificate that will be treated as trusted
          insecure: true  # Validate server hostname in server certificate
      subscribe:
        qos: 0   # Default QoS for subscribing
        topics:
        - - '#'
          -
      publish:
        qos: 0         # Default QoS when publishing values
        retain: false  # Default retain flag when publishing values
      general:
        listen_only: false   # If True HABApp does not publish any value to the broker
    openhab:
      connection:
        url: 'https://oh.domain.com'   # Connect to this url. Empty string ("") disables the connection.
        user: 'REDACTED'
        password: 'REDACTED'
        verify_ssl: true             # Check certificates when using https
      general:
        listen_only: false      # If True HABApp does not change anything on the openHAB instance.
        wait_for_openhab: true  # If True HABApp will wait for a successful openHAB connection before loading any rules on startup
      ping:
        enabled: true      # If enabled the configured item will show how long it takes to send an update from HABApp and get the updated value back from openHAB in milliseconds
        item: HABApp_Ping  # Name of the Numberitem
        interval: 10       # Seconds between two pings
````

Does anyone have any suggestions on what the issue could be?
Do "watchers" work ok in Kubernetes pods?
Could there be something wrong in where I have put my files?
Currently have:
/habapp/config   <--- config.yml & logging.yml
/habapp/log   <--- log files being generated
/habapp/rules   <--- python rules files

Thanks,
Richie

**Comment by spacemanspiff2007** [comment]
The directory under config can not be the directory of the `config.yml`

**Comment by spacemanspiff2007** [comment]
No, the config entry in the `config.yml` is for textual thing config files, something that is hardly used.
So you `config.yml` goes in `/habapp/config`
`config` in `config.yml` gets set to `/habapp/config/config`

**Comment by RichieRogers** [comment]
Hi, 
Ahh, now I get you.
I was just replying to say that when I did my default deployment into Kubernetes for HABApp, the config.yml WAS in /habapp/config.
What needs changing is the textual config path in the config.yml.

Right, will try that.

Thanks,
Richie

**Comment by RichieRogers** [comment]
Hi,
That works :)
Will see how much further I get now.

Thanks,
Richie
