### ISSUE TITLE
Problem with run.at()

### ISSUE THREAD

**Issue by HarrysLapTimer** [spacemanspiff2007/HABApp#461]
I'm pretty new to HABApp and have started migrating a huge number of rules from openHAB2.5 Jython to openHAB4.x and HABApp.

I struggle with using self.run.at(). Here is the sample in the docs and the error message I receive:

```
from HABApp import Rule
from HABApp.rule.scheduler import filter, trigger

class MyTriggerRule(Rule):
    def __init__(self):
        super().__init__()
        # Run the function every day at 12
        self.run.at(self.run.trigger.time('12:00:00'), self.dummy_func)
        # ------------------------------------------------------------------------------
        # The trigger and filter factories are available as a property on self.run,
        # however they can also be used separately when imported
        # This is exactly the same as above
        self.run.at(trigger.time('12:00:00'), self.dummy_func)
        ...   
```

The error I get is `ImportError: cannot import name 'filter' from 'HABApp.rule.scheduler' (/opt/habapp/lib/python3.11/site-packages/HABApp/rule/scheduler/__init__.py)`. Removing `filter` (which is not used in the snippet) results in the same error for trigger. Stripping the snippet down to use self.run.trigger only

```
from HABApp import Rule

class MyTriggerRule(Rule):
	def __init__(self):
		super().__init__()

		# Run the function every day at 12
		self.run.at(self.run.trigger.time('12:00:00'), self.dummy_func)

	def dummy_func(self):
		pass

MyTriggerRule()
```

results in this stack trace:
```
Traceback (most recent call last):
2024-11-23 17:35:07.704 [ERROR] [HABApp.Rules                        ] -   File "/opt/habapp/lib/python3.11/site-packages/HABApp/rule_manager/rule_file.py", line 79, in load
2024-11-23 17:35:07.704 [ERROR] [HABApp.Rules                        ] -     self.create_rules(created_rules)
2024-11-23 17:35:07.705 [ERROR] [HABApp.Rules                        ] -   File "/opt/habapp/lib/python3.11/site-packages/HABApp/rule_manager/rule_file.py", line 69, in create_rules
2024-11-23 17:35:07.705 [ERROR] [HABApp.Rules                        ] -     runpy.run_path(str(self.path), run_name=str(self.path), init_globals=rule_hook.in_dict())
2024-11-23 17:35:07.705 [ERROR] [HABApp.Rules                        ] -   File "<frozen runpy>", line 291, in run_path
2024-11-23 17:35:07.705 [ERROR] [HABApp.Rules                        ] -   File "<frozen runpy>", line 98, in _run_module_code
2024-11-23 17:35:07.705 [ERROR] [HABApp.Rules                        ] -   File "<frozen runpy>", line 88, in _run_code
2024-11-23 17:35:07.705 [ERROR] [HABApp.Rules                        ] -   File "/etc/openhab/habapp/rules/test.py", line 74, in test.py
2024-11-23 17:35:07.705 [ERROR] [HABApp.Rules                        ] -     MyTriggerRule()
2024-11-23 17:35:07.705 [ERROR] [HABApp.Rules                        ] -   File "/etc/openhab/habapp/rules/test.py", line 69, in __init__
2024-11-23 17:35:07.705 [ERROR] [HABApp.Rules                        ] -     self.run.at(self.run.trigger.time('12:00:00'), self.dummy_func)
2024-11-23 17:35:07.705 [ERROR] [HABApp.Rules                        ] -                 ^^^^^^^^^^^^^^^^
2024-11-23 17:35:07.705 [ERROR] [HABApp.Rules                        ] - AttributeError: 'HABAppSchedulerView' object has no attribute 'trigger'

```

Any idea? I use the latest HABApp version installed from openhabian-config which is 24.11.0.

**Comment by spacemanspiff2007** [comment]
> I use the latest HABApp version installed from openhabian-config which is 24.11.0.

I think you are still running an older version - maybe 24.8.0?
When you have have updated HABApp please ensure that you do a restart.
Please check the HABApp.log, one of the first entries is the version number.
What version are you running?

**Comment by HarrysLapTimer** [comment]
This is what I see when starting HABApp:

openhabian@openhabian:/etc/openhab/habapp/rules $ /opt/habapp/bin/python3 /opt/habapp/bin/habapp
```
  _   _    _    ____    _
 | | | |  / \  | __ )  / \   _ __  _ __
 | |_| | / _ \ |  _ \ / _ \ | '_ \| '_ \
 |  _  |/ ___ \| |_) / ___ \| |_) | |_) |
 |_| |_/_/   \_|____/_/   \_| .__/| .__/
                            |_|   |_|
                                        24.11.0
Config file "config.yml" not found!
Checked folders:
 - /etc/openhab/habapp/rules/HABApp
 - /etc/openhab/habapp/HABApp
 - /etc/openhab/HABApp
 - /home/openhabian/HABApp
Please create file or specify a folder with the "-c" arg switch.
```

**Comment by HarrysLapTimer** [comment]
Me again. It turned out the problem disappeared after fixing some issues I had introduced into logging... Don't ask why most of the code worked but crashed when setting up the trigger. No idea...

Thanks for looking into this instantly!

I appreciate the effort you have put into HABApp to keep a modern Python path for openHAB!
