### ISSUE TITLE
Fix crash for empty working dir

### ISSUE THREAD

**Issue by spacemanspiff2007** [spacemanspiff2007/HABApp#49]
````
Traceback (most recent call last):
  File "/opt/habapp/lib/python3.6/site-packages/HABApp/__main__.py", line 117, in main
    app.load_config(config_folder=find_config_folder(args.config))
  File "/opt/habapp/lib/python3.6/site-packages/HABApp/__main__.py", line 20, in find_config_folder
    working_dir.with_name('HABApp'),            # current working dir
  File "/usr/lib/python3.6/pathlib.py", line 817, in with_name
    raise ValueError("%r has an empty name" % (self,))
ValueError: PosixPath('/') has an empty name
PosixPath('/') has an empty name
PosixPath('/') has an empty name
````

**Comment by spacemanspiff2007** [comment]
It's ``with_name()`` that raises the ValueError because the working dir is ``/``

**Comment by spacemanspiff2007** [comment]
Fixed with https://github.com/spacemanspiff2007/HABApp/pull/54
