### ISSUE TITLE
ConfigStatusInfoEvent raises error

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#99]
Just upgraded to OH 2.5.0-1, I'm seeing these errors:
```
2019-12-20 14:44:51,528[ HABApp.openhab.Connection]ERROR|        on_sse_event: Unknown Event: ConfigStatusInfoEvent
2019-12-20 14:44:51,529[ HABApp.openhab.Connection]ERROR|        on_sse_event: Traceback (most recent call last):
2019-12-20 14:44:51,529[ HABApp.openhab.Connection]ERROR|        on_sse_event:   File "/home/nick/Scripts/HABApp/HABApp/openhab/events/__init__.py", line 24, in get_event
2019-12-20 14:44:51,530[ HABApp.openhab.Connection]ERROR|        on_sse_event:     return __event_lookup[event_type](_in_dict)
2019-12-20 14:44:51,530[ HABApp.openhab.Connection]ERROR|        on_sse_event: KeyError: 'ConfigStatusInfoEvent'
2019-12-20 14:44:51,530[ HABApp.openhab.Connection]ERROR|        on_sse_event:
2019-12-20 14:44:51,531[ HABApp.openhab.Connection]ERROR|        on_sse_event: During handling of the above exception, another exception occurred:
2019-12-20 14:44:51,531[ HABApp.openhab.Connection]ERROR|        on_sse_event:
2019-12-20 14:44:51,532[ HABApp.openhab.Connection]ERROR|        on_sse_event: Traceback (most recent call last):
2019-12-20 14:44:51,532[ HABApp.openhab.Connection]ERROR|        on_sse_event:   File "/home/nick/Scripts/HABApp/HABApp/openhab/oh_connection.py", line 105, in on_sse_event
2019-12-20 14:44:51,532[ HABApp.openhab.Connection]ERROR|        on_sse_event:     event = get_event(event_dict)
2019-12-20 14:44:51,533[ HABApp.openhab.Connection]ERROR|        on_sse_event:   File "/home/nick/Scripts/HABApp/HABApp/openhab/events/__init__.py", line 26, in get_event
2019-12-20 14:44:51,533[ HABApp.openhab.Connection]ERROR|        on_sse_event:     raise ValueError(f'Unknown Event: {event_type:s}')
2019-12-20 14:44:51,534[ HABApp.openhab.Connection]ERROR|        on_sse_event: ValueError: Unknown Event: ConfigStatusInfoEvent
```
While I'm trying to fix the usual breaking changes in OH. I'm assuming these will stop once I get my things and items stable again, but it might be as well to handle them gracefully.

I just updated to V 11.0 by the way - no problems other than the above so far...

**Comment by spacemanspiff2007** [comment]
I can't reproduce this error - can you check again with 0.12?
If it still occurs there please reopen this issue.

**Comment by NickWaterton** [comment]
Have version 0.12 and still seeing these errors:
```
2020-01-31 12:20:36,266[                    MyRule]ERROR|            on_error: Error: Error in on_sse_event: Unknown Event: ConfigStatusInfoEvent for {'topic': 'smarthome/things/zwave:device:controller:node9/config/status', 'payload': '{"configStatusMessages":[]}', 'type': 'ConfigStatusInfoEvent'}
Traceback (most recent call last):
KeyError: 'ConfigStatusInfoEvent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nick/Scripts/HABApp/HABApp/util/wrapper.py", line 79, in f
    return func(*args, **kwargs)
  File "/home/nick/Scripts/HABApp/HABApp/openhab/oh_connection.py", line 103, in on_sse_event
    event = get_event(event_dict)
  File "/home/nick/Scripts/HABApp/HABApp/openhab/events/__init__.py", line 27, in get_event
    raise ValueError(f'Unknown Event: {event_type:s} for {_in_dict}')
ValueError: Unknown Event: ConfigStatusInfoEvent for {'topic': 'smarthome/things/zwave:device:controller:node9/config/status', 'payload': '{"configStatusMessages":[]}', 'type': 'ConfigStatusInfoEvent'}
2020-01-31 12:20:36,524[                    MyRule]ERROR|            on_error: Error: Error in on_sse_event: Unknown Event: ConfigStatusInfoEvent for {'topic': 'smarthome/things/zwave:device:controller:node9/config/status', 'payload': '{"configStatusMessages":[]}', 'type': 'ConfigStatusInfoEvent'}
Traceback (most recent call last):
KeyError: 'ConfigStatusInfoEvent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nick/Scripts/HABApp/HABApp/util/wrapper.py", line 79, in f
    return func(*args, **kwargs)
  File "/home/nick/Scripts/HABApp/HABApp/openhab/oh_connection.py", line 103, in on_sse_event
    event = get_event(event_dict)
  File "/home/nick/Scripts/HABApp/HABApp/openhab/events/__init__.py", line 27, in get_event
    raise ValueError(f'Unknown Event: {event_type:s} for {_in_dict}')
ValueError: Unknown Event: ConfigStatusInfoEvent for {'topic': 'smarthome/things/zwave:device:controller:node9/config/status', 'payload': '{"configStatusMessages":[]}', 'type': 'ConfigStatusInfoEvent'}
```

**Comment by spacemanspiff2007** [comment]
It's fixed in the dev branch, I just forgot to update this issue
